<fieldset class="card grid sm:grid-cols-2 gap-4" data-row-item>
    <div class="field"><label class="label" for="ps-type-{{ $i }}">Type</label><select id="ps-type-{{ $i }}" name="items[{{ $i }}][type]" class="input">@foreach(['ALEVEL'=>'A-levels','IB'=>'IB Diploma','FOUNDATION'=>'Foundation / pathway programme','DEGREE'=>'University degree','OTHER'=>'Other (e.g. ND/HND, JUPEB)'] as $v=>$l)<option value="{{ $v }}" @selected(($it['type'] ?? '')===$v)>{{ $l }}</option>@endforeach</select></div>
    <div class="field"><label class="label" for="ps-status-{{ $i }}">Status</label><select id="ps-status-{{ $i }}" name="items[{{ $i }}][status]" class="input">@foreach(['completed'=>'Completed','in_progress'=>'In progress','planned'=>'Planned'] as $v=>$l)<option value="{{ $v }}" @selected(($it['status'] ?? 'completed')===$v)>{{ $l }}</option>@endforeach</select></div>
    <div class="field sm:col-span-2"><label class="label" for="ps-inst-{{ $i }}">Institution</label><input id="ps-inst-{{ $i }}" name="items[{{ $i }}][institution]" value="{{ $it['institution'] ?? '' }}" class="input"></div>
    <div class="field"><label class="label" for="ps-award-{{ $i }}">Award / subjects</label><input id="ps-award-{{ $i }}" name="items[{{ $i }}][award]" value="{{ $it['award'] ?? '' }}" class="input" placeholder="e.g. Biology, Chemistry, Maths · or BSc Biochemistry"></div>
    <div class="field"><label class="label" for="ps-result-{{ $i }}">Result</label><input id="ps-result-{{ $i }}" name="items[{{ $i }}][result]" value="{{ $it['result'] ?? '' }}" class="input" placeholder="e.g. AAB · 2:1 · CGPA 4.2/5"></div>
    <div class="field"><label class="label" for="ps-start-{{ $i }}">Start year</label><input id="ps-start-{{ $i }}" name="items[{{ $i }}][start_year]" inputmode="numeric" value="{{ $it['start_year'] ?? '' }}" class="input"></div>
    <div class="field"><label class="label" for="ps-end-{{ $i }}">End year</label><input id="ps-end-{{ $i }}" name="items[{{ $i }}][end_year]" inputmode="numeric" value="{{ $it['end_year'] ?? '' }}" class="input"></div>
    <div class="sm:col-span-2 text-right"><button type="button" data-remove-row class="btn btn-tertiary text-[0.875rem]">Remove</button></div>
</fieldset>
