// Bakes the Lucide icons the site uses (ISC licence, brand/fonts/LICENSES.md) into resources/views/components/icon.blade.php.
// Usage: npm i --no-save lucide-static && ICON_MODULES=<node_modules> node ops/design/build-icons.mjs
import fs from 'node:fs';
const dir = (process.env.ICON_MODULES || 'node_modules') + '/lucide-static/icons/';
const names = ['map-pin', 'route', 'stethoscope', 'graduation-cap', 'school', 'book-open', 'pound-sterling', 'calendar-days', 'clipboard-check',
  'file-text', 'shield-check', 'search', 'arrow-right', 'check', 'x', 'globe', 'user-round', 'scale', 'badge-check', 'compass', 'landmark',
  'files', 'list-checks', 'clock', 'mail', 'message-circle', 'external-link', 'chevron-right', 'heart-pulse', 'flag', 'plane', 'microscope',
  'circle-help', 'layers', 'lock', 'sparkles', 'info'];
const inner = {};
for (const n of names) {
  const svg = fs.readFileSync(dir + n + '.svg', 'utf8');
  inner[n] = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '').trim();
}
const php = Object.entries(inner).map(([k, v]) => `        '${k}' => '${v.replace(/'/g, "\\'")}',`).join('\n');
fs.writeFileSync('resources/views/components/icon.blade.php', `{{-- Lucide icons (ISC licence), generated by ops/design/build-icons.mjs; decorative unless a label is given --}}
@props(['name', 'label' => null, 'size' => 20, 'stroke' => 1.75])
@php
    $paths = [
${php}
    ];
@endphp
<svg {{ $attributes->merge(['class' => 'shrink-0']) }} width="{{ $size }}" height="{{ $size }}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="{{ $stroke }}" stroke-linecap="round" stroke-linejoin="round" @if($label) role="img" aria-label="{{ $label }}" @else aria-hidden="true" focusable="false" @endif>{!! $paths[$name] ?? '' !!}</svg>
`);
console.log(`icon.blade.php: ${names.length} icons`);
