"""Regenerates data/seo/decision-register.csv from the rows declared below (one call per query family).
Run from the repository root: python3 ops/seo/build-register.py. Edit rows here, never the CSV by hand; the
Semrush importer may fill volume/keyword_difficulty cells in the CSV, so re-run the importer after regenerating."""
import csv
NA="DATA UNAVAILABLE (Semrush: no API units; owner lookup pending)"
D="2026-10-03"
rows=[]
def add(cluster,family,examples,intent,relevance,serp,competing,current,recommended,supporting,score,sources,status,reason,review="2027-01-15",db="ng"):
    rows.append(dict(id=f"{cluster}{sum(1 for r in rows if r['cluster']==cluster)+1:02d}",cluster=cluster,query_family=family,example_queries=examples,intent=intent,country_db=db,nigerian_relevance=relevance,volume=NA,keyword_difficulty=NA,serp_features_observed=serp,competing_urls=competing,current_url=current,recommended_page=recommended,supporting_pages=supporting,relevance_score=score,sources=sources,status=status,status_reason=reason,decided_on=D,review_due=review))

# A — Commercial (our service)
add("A","apply online for UK medicine from Nigeria / medicine application help Nigeria","apply to study medicine in uk from nigeria; uk medicine application help nigeria; medical school application service nigeria","commercial/transactional","HIGH","agents, North Cyprus intent hijack; no UK-medicine-only service page observed","northcypruseducation.com; studyin-uk.com; ukeas.com","/apply-online","/apply-online","/apply-online/services; /apply-online/eligibility; /admissions/how-to-apply",5,"02 §A q1-4; 05 table; 11 terminology","PUBLISHED","Gateway page is the principal CTA target of every landing page; prices shown only once set by the owner (no fabricated fees).")
add("A","UK medicine application service prices / consultant fees","medicine admissions consultant fee; uk university application agent cost nigeria","commercial","MEDIUM","competitors hide prices (05)","theukcatpeople.co.uk; medicmind.co.uk","/apply-online/services","/apply-online/services","/apply-online; /refund-policy; /application-terms",4,"05 §prices","PUBLISHED","Deliverables, exclusions and the fee disclaimer are published; the fees themselves are not public (owner decision 2026-10-04): they are shown in the portal once a profile has been reviewed, and always before payment. The page targets the service-scope intent, not price queries.")
add("A","eligibility check for UK medicine (Nigerian qualifications)","am i eligible to study medicine in uk; check eligibility medicine uk waec","lead capture","HIGH","none (tools do not rank; captured via landing pages)","—","/apply-online/eligibility","/apply-online/eligibility","/requirements; /requirements/waec; /study-medicine-in-the-uk/foundation-routes",5,"07 rules","PUBLISHED","Conversion tool, not a search target; every informational page links to it as the next step. Noindex not required: it has unique explanatory copy and a FAQ-free answer.")
add("A","are you an agent / official representative of UK universities","uk university agents in nigeria; official representative university nigeria","navigational/trust","HIGH","studentship.com.ng agent list; university 'find a representative' pages","studentship.com.ng/uk-universities-agents-nigeria/","/our-status","/our-status","/about; /how-we-verify; /faq#q40",4,"11 terminology; 02 §C q40","PUBLISHED","We never claim official agent status; the page states exactly what we are and are not. Supports trust, not traffic. Upgraded 2026-10-03 from 306 to about 850 words: the sector vocabulary (agent, representative, referral partner, sub-agent, counsellor, UCAS registered centre, British Council training) with our position on each, a four-step check anyone can run on any service, FAQ 40 with schema.")

# B — Medicine (study medicine in the UK, general)
add("B","study medicine in the UK (international, generic)","study medicine in uk; how to study medicine in the uk; mbbs in uk for international students","informational","MEDIUM","strong UK prep companies (themedicportal, medify), universities, UCAS","themedicportal.com; medify.co; ucas.com","/study-medicine-in-the-uk","/study-medicine-in-the-uk","/study-medicine-in-the-uk/from-nigeria; /medical-schools; /requirements; /fees",3,"02 §A q1-3","PUBLISHED","Pillar page. Generic head term is UK-competitor dominated; we hold it only as the parent of the Nigerian landing page and do not chase it with volume content. Upgraded 2026-10-03 from 598 to about 1,250 words: what the degree is, three routes, where international students can go (live counts), the calendar, cost, after graduation with GMC facts, an honest decision section and three FAQs with schema.")
add("B","why study medicine in the UK / is UK medicine right for me","is medicine the right course to study in the uk; why study medicine in uk","informational","MEDIUM","Nairaland thread; agent blogs","nairaland.com/8665379","—","/study-medicine-in-the-uk (section) — no separate page","/working-in-the-uk; /fees/cost-of-studying-medicine-in-the-uk",2,"02 §A q17; register row 24","RESEARCH","Register row 24: fact-led content depends on research 10 gaps (MLA, Foundation Programme prioritisation policy in flux). Re-decide with Semrush ng/uk volumes; if built, one page maximum.")
add("B","MBBS UK for Nigerian students (ambiguous)","mbbs uk nigerian students; mbbs in uk from nigeria","informational (ambiguous: study vs Nile/GMC news)","HIGH","Nile University GMC-approval news cluster dominates","honoris.net; dailytrust.com; globaladmissions.com","/study-medicine-in-the-uk/from-nigeria","/study-medicine-in-the-uk/from-nigeria (disambiguation paragraph)","/faq",3,"02 §A q3","UPDATE","Core landing already covers it; add an explicit 'MBBS vs MBChB/MBBS naming' disambiguation sentence and link the FAQ on Nigerian MBBS recognition. No separate page: intent splits and the news intent is not ours.")

# C — Nigerian-specific core
add("C","study medicine in the UK from Nigeria (core)","study medicine in uk from nigeria; medicine in uk for nigerian students; how to study medicine in uk from nigeria","informational→commercial","HIGH","1 consultancy landing (theukcatpeople), news, listicles, North Cyprus agent; no official source ranks","theukcatpeople.co.uk/application-guide/ucas/study-medicine-in-the-uk-from-nigeria; leadingtuition.co.uk/blog/ucat-nigerian-students-uk-medicine; northcypruseducation.com","/study-medicine-in-the-uk/from-nigeria","/study-medicine-in-the-uk/from-nigeria","/requirements/waec; /admissions/ucat; /fees; /medical-schools; /apply-online",5,"02 §A q1-4, §D; 05 ranks 1-3","PUBLISHED","Primary asset. Internal-link audit (2026-10-03) found only one in-body link to it from other pages: fixed by adding contextual links from the home page, hubs and FAQ (see DECISION-ENGINE.md §6).")
add("C","medical universities in UK for Nigerians / UK medical school Nigeria (list intent)","medical universities in uk for nigerian students; uk medical schools for nigerians; best uk universities for medicine for nigerians","informational/commercial (list)","HIGH","unsourced blog lists; scholarship listicles","studentship.com.ng; twinkl.pt; excelsiorscholarships.com","/medical-schools","/medical-schools (filter: accepts international) + Nigerian-applicant block on each university page","/study-medicine-in-the-uk/from-nigeria; /requirements/waec",5,"02 §A q4; 06","PUBLISHED","Served by the directory with per-school published statements rather than a 'best for Nigerians' list (rankings REJECTED, see S/REJECTED rows).")
add("C","Nigerian student stories / news about admission to UK medicine","nigerian girl offered admission medicine uk","news/navigational","LOW","Nigerian news sites","icirnigeria.org; dailytrust.com","—","none","—",1,"02 §A q2","REJECTED","News intent; we publish no testimonials or student stories (owner rule: no fabricated or unverifiable social proof).")

# D — UK medical schools (directory)
add("D","UK medical schools that accept international students","uk medical schools that accept international students; which uk universities accept international medicine students; how many international places medicine uk","informational/commercial","HIGH","strong: prep companies, THE; no Nigeria angle","nextgenmedprep.com/medical-schools/international-students; bluepeanut.com; timeshighereducation.com","/medical-schools","/medical-schools","/medical-schools/{university}; /fees; /admissions/ucat",5,"02 §A q14, §C q26-27; 06","PUBLISHED","Directory with international_policy, places, test, route and verification dates. Filter combinations stay query-string + canonical to the directory until GSC shows demand (row D03).")
add("D","individual UK medical school for international / Nigerian applicants","{university} medicine international entry requirements; {university} nigeria entry requirements medicine","informational","HIGH","universities' own country pages rank (Aberdeen, Manchester, Cardiff, Edinburgh)","abdn.ac.uk; manchester.ac.uk; cardiff.ac.uk; ed.ac.uk","/medical-schools/{university}","/medical-schools/{university} (only schools open to international applicants with ≥3 verified fields are indexable)","/requirements/waec; /fees; /admissions/ucat",4,"02 §A q5; 06; 07","PUBLISHED","University pages are indexable only when they carry a Nigerian-applicant block with published statements; home-only schools are listed in the directory and are noindex. Prevents thin university pages. 2026-10-03: every record now adds a computed 'what this means if you are applying from Nigeria' section (policy, places, WAEC/NECO, English, foundation, graduate entry, each switching on whether a fact is published) and 'how to apply to this school' (route, test, UCAS deadline and UCAT window facts), plus Course schema with an Offer only for a VERIFIED fee; 550–700 words before staff verification.")
add("D","whitelisted directory filters (no UCAT / accepting international / GAMSAT)","uk medical schools without ucat; medical schools uk no ucat international; gamsat medical schools uk international","informational/commercial","MEDIUM","prep company listicles","themedicportal.com; medify.co","/medical-schools?test=… (canonical → /medical-schools)","static filter URLs only if Semrush ng/uk or GSC confirms demand","/admissions/ucat; /requirements/nigerian-degree-graduate-entry",3,"register row 30; 18.1","RESEARCH","Needs Semrush or GSC evidence before creating indexable filter pages; otherwise they stay noindex query strings. Owner lookup: 'uk medical schools no ucat' (uk, ng).")
add("D","compare medical schools","compare uk medical schools international fees","tool","MEDIUM","—","—","—","/medical-schools/compare (noindex tool)","/medical-schools",2,"register row 28","VALIDATED","Build when ≥20 schools have fee + test + route + deadline verified; it will be a noindex tool, not a landing page.")
add("D","best / top medical schools in the UK (for Nigerians)","best medical schools in uk; top uk medical schools for nigerian students; ranking medical schools uk","commercial (list)","MEDIUM","rankings sites, Nairaland","nairaland.com/7408807; timeshighereducation.com","/faq#q15","FAQ answer only","/medical-schools",2,"02 §C q15; register C","REJECTED","No defensible methodology; owner rule forbids rankings and winner badges. FAQ 15 explains why and routes to the directory.")

# E — Requirements (general)
add("E","entry requirements to study medicine in the UK (international / Nigerian)","medicine entry requirements uk for nigerian students; what do i need to study medicine in uk; requirements to study medicine in uk international students","informational","HIGH","university country pages + 2 consultancies","abdn.ac.uk/study/international/country-territory/nigeria/entry/; manchester.ac.uk/…/nigeria/entry-requirements/; gostudyin.com","/requirements","/requirements","/requirements/waec; /requirements/a-levels; /requirements/english-language; /admissions/ucat",5,"02 §A q5; 07","PUBLISHED","Hub answering the 'what do I need' question with a structured checklist and per-qualification child pages. 2026-10-03: added the 'which route is yours' table (what you hold → published route → what to check → page) and four FAQs with schema; 427 to about 950 words.")
add("E","A-levels for UK medicine from Nigeria (Cambridge International)","a level requirements medicine uk; cambridge a level nigeria medicine uk; a level schools nigeria uk medicine","informational→commercial","HIGH","Nigerian school directories, news","nigeriaprivateschools.com; nairaland.com/1837366","/requirements/a-levels","/requirements/a-levels","/medical-schools; /admissions/ucat; /study-medicine-in-the-uk/foundation-routes",4,"02 §A q9, §C q10-11; 07 A-level column","PUBLISHED","Typical A100 grade requirements and subject rules sourced per school; we name no A-level schools in Nigeria (no recommendations without evidence). Upgraded 2026-10-03 from 643 to about 1,400 words: how to read an offer, Cambridge International sittings and predicted grades, IB equivalence, the A-level years and UCAT in order, two FAQs with schema.")
add("E","English language requirements for medicine (IELTS, WAEC English)","ielts requirement medicine uk; do nigerians need ielts for uk university; waec english accepted uk university","informational","HIGH","thin; university English pages; agent help centres","assist.applyboard.com (NECO article); leadingtuition.co.uk","/requirements/english-language","/requirements/english-language","/requirements/waec; /requirements/neco; /fees/cost-of-studying-medicine-in-the-uk",4,"02 §C q5, q21; 07 English column","PUBLISHED","Per-school IELTS bands and where WAEC/NECO English counts; the two assessment layers (school and visa) explained, with the GOV.UK wording marked as not yet verified. Upgraded 2026-10-03 from 492 to about 1,250 words with two FAQs and schema.")
add("E","age / fee status / UK ENIC comparability questions","minimum age medicine uk international; uk enic nigerian degree equivalent","informational (long-tail)","MEDIUM","none specific","—","—","FAQ answers; sections on /requirements/nigerian-degree-graduate-entry","/requirements",2,"07 §planned (DATA UNAVAILABLE search budget)","RESEARCH","Research 07 could not retrieve age and fee-status rules (search budget). Collect sources first; FAQ-level answers only.")

# F — WAEC
add("F","can I study medicine in the UK with WAEC","can i study medicine in uk with waec; waec medicine uk; is waec accepted in uk universities for medicine; waec gcse equivalent uk","informational (question, high anxiety)","HIGH","two consultancy guides, forum threads, contradictory answers","theukcatpeople.co.uk (Nigeria guide); thestudentroom.co.uk t=7404771; nairaland.com/6081067","/requirements/waec","/requirements/waec","/study-medicine-in-the-uk/foundation-routes; /requirements/a-levels; /requirements/english-language; /apply-online/eligibility",5,"02 §A q6, §C q1-3, q7; 07 WAEC column","PUBLISHED","Highest-confidence Nigerian demand. Per-university published statement table with source and verified date; honest 'WAEC alone is the GCSE layer' framing.")
add("F","can I study medicine and surgery with this WAEC result (grade-specific)","can i study medicine and surgery with this result; waec grades for medicine uk; b3 c4 waec medicine uk","informational (long-tail)","HIGH","Nairaland threads only","nairaland.com/5329415; nairaland.com/3934860","/requirements/waec#what-this-means","/requirements/waec 'What this means for you' section + eligibility check","/apply-online/eligibility",4,"02 §C q7","PUBLISHED","Served in-page: grade thresholds appear only where a school publishes them (e.g. QMUL IFY 6 credits at C4; Nottingham foundation 3 Bs 2 Cs). No separate page.")

# G — NECO
add("G","NECO and UK medicine / NECO accepted in UK","neco medicine uk; which uk universities accept neco; does neco english replace ielts","informational (question)","HIGH","near-empty; one agent help-centre article","assist.applyboard.com/…/Studying-in-the-UK-with-NECO; teezab.com","/requirements/neco","/requirements/neco","/requirements/waec; /requirements/english-language",4,"02 §A q7, §C q4-5; 07 (Edinburgh, Aberdeen, QUB, Lancashire name NECO)","UPDATE","Page is thin (379 words). Upgrading on 2026-10-03 with the explicit NECO mentions table, the NECO-English acceptance list and the 'silent schools' rule; stays a separate URL because statements differ (Edinburgh names NECO; most do not).")
add("G","JAMB / UTME and UK medicine","jamb medicine uk; does jamb score count for ucas","informational (one-line answer)","MEDIUM","very weak / spam","leadingtuition.co.uk","/faq#q6","FAQ answer only","/requirements",1,"02 §A q8, §C q6; register row 33","REJECTED","Demand is domestic JAMB; the UK angle is one sentence (UCAS does not use JAMB). FAQ only, never a page.")

# H — UCAT
add("H","UCAT in Nigeria (centres, booking, dates)","ucat nigeria; ucat test centre lagos; ucat abuja; how to book ucat from nigeria; ucat 2026 dates","transactional/logistics","HIGH","one tutoring blog; no official Nigeria page","leadingtuition.co.uk/blog/ucat-nigerian-students-uk-medicine; ucat.ac.uk","/admissions/ucat","/admissions/ucat","/admissions/ucas-deadlines-2027; /medical-schools; /study-medicine-in-the-uk/from-nigeria",5,"02 §A q12-13, §C q18-20; 09 UCAT section","PUBLISHED","Strongest single content gap. Dates, structure, fee and Pearson VUE logistics are topic facts (ucat-2026) with verification status; 'if you have no UCAT today' section routes to foundation/direct schools. Upgraded 2026-10-03 from 620 to about 1,500 words: booking and access-arrangement deadlines as facts, booking from Nigeria step by step, how schools use the score (no invented cut-offs), preparation without paid courses, three FAQs with schema.")
add("H","UCAT score needed as an international / Nigerian applicant","ucat score for international students; what ucat score do i need uk medicine","informational","MEDIUM","prep companies","medify.co; themedicportal.com","/faq#q20","FAQ + per-school threshold facts on university pages","/admissions/ucat; /medical-schools",3,"02 §C q20; 07 (UCL 3060 agent-lead, QMUL 3rd decile)","PUBLISHED","Thresholds published per school only where official; FAQ 20 explains that cut-offs move yearly. No 'score predictor' page.")
add("H","UCAT preparation / courses","ucat preparation nigeria; ucat course online","commercial (tutoring)","MEDIUM","strong: Medic Mind, Medify, TheMedicPortal","medicmind.co.uk; medify.co","—","none","/admissions/ucat",1,"05 rows 7-8","REJECTED","Tutoring market is not our service and is saturated; we link to the official UCAT practice materials instead.")

# I — UCAS
add("I","admissions process hub (UCAS, UCAT, interviews, offers, visa in order)","uk medicine admissions process international; how does medical school admission work uk; medicine application timeline uk","informational","HIGH","UCAS, Medical Schools Council, prep companies","ucas.com; medschools.ac.uk","/admissions","/admissions","/admissions/ucat; /admissions/ucas-deadlines-2027; /admissions/how-to-apply",4,"09; register rows 15-17","PUBLISHED","Hub ordering the whole process for an applicant in Nigeria; children carry the specific queries. 2026-10-03: added the 'where are you today' table (position → meaning → next step) and three FAQs with schema; 470 to about 850 words.")
add("I","UCAS deadline for medicine 2027 entry / international deadline","ucas medicine deadline 2027; 15 october deadline medicine international; ucas deadline for international students medicine","informational, time-critical","HIGH","UCAS itself","ucas.com","/admissions/ucas-deadlines-2027","/admissions/ucas-deadlines-2027 (roll over each August)","/admissions/ucat; /admissions/how-to-apply; /study-medicine-in-the-uk/from-nigeria",4,"02 §A q16; 09 UCAS section","PUBLISHED","Nigeria-specific calendar (UCAT → UCAS → interview → offer → CAS → visa → TB test). Year in slug is deliberate for the cycle page; 301 on rollover per architecture 18.1. Upgraded 2026-10-03 from 526 to about 1,050 words: what each deadline means, the document timeline, the CAS-to-visa risk window, two FAQs with schema.")
add("I","how to apply to UK medicine from Nigeria (UCAS vs direct)","how to apply for medicine in uk from nigeria; ucas application nigeria step by step; direct application medical school uk","informational→action","HIGH","Nairaland step-by-step thread; agents","nairaland.com/1948639; nairaland.com/4071072","/admissions/how-to-apply","/admissions/how-to-apply","/apply-online; /admissions/ucas-deadlines-2027; /medical-schools",5,"02 §C q12-13; 09","PUBLISHED","4+1 rule, three-question statement, reference routes, document upload, Nigerian document list, direct-application schools, missed-deadline options, after-submission steps and what we do and do not do. Upgraded 2026-10-03 from 479 to about 1,350 words with three FAQs and schema.")
add("I","personal statement (3 questions) and reference for medicine","ucas personal statement medicine 2027 three questions; medicine personal statement international","informational","MEDIUM","widely served by UK prep companies","themedicportal.com; medify.co","—","/admissions/personal-statement (later, to support Tier 2)","/admissions/how-to-apply",2,"register row 27","VALIDATED","Portal checklist covers documents; a public statement page waits until the service tier needs it. Not a traffic play.")

# J — International students (places, acceptance)
add("J","international acceptance rates / places at UK medical schools","uk medical school international acceptance rate; how many international students medicine uk","informational","MEDIUM","bluepeanut, nextgenmedprep listicles","bluepeanut.com; nextgenmedprep.com","/faq#q27","FAQ + international_places facts per school","/medical-schools",3,"02 §C q26-27; 06 '# intl' column","PUBLISHED","We publish the places figure per school only where official (19 facts recorded); no computed 'acceptance rates' (no denominator data).")
add("J","scholarships for Nigerian students to study medicine in the UK","scholarships to study medicine in uk for nigerian students; scholarship study abroad with waec","informational/commercial","HIGH","unverified listicles","excelsiorscholarships.com; dofmar.com; nairaland.com/8031932","/faq#q28","FAQ answer with the honest position (very limited partial awards; Medicine usually excluded)","/fees",2,"02 §A q27, §C q28-29; 08 §5","REJECTED","Listicle intent would mislead: only tiny partial awards exist for international medicine. One FAQ, no page; re-open only if a verified, currently open scheme exists.")

# K — Fees and costs
add("K","UK medical school fees for international students","medical school fees uk international students; medicine tuition fees uk international 2027; cheapest medical school uk international","informational/commercial","HIGH","undated conflicting figures; prep companies + spam","theukcatpeople.co.uk/post/uk-medical-school-tuition-fees-for-international-students; bluepeanut.com/…/cheapest-uk-medical-schools","/fees","/fees","/fees/cost-of-studying-medicine-in-the-uk; /medical-schools/{university}; /apply-online",5,"02 §A q11-12,15, §C q22-25; 08","PUBLISHED","Dated per-school table (40 fee facts), approximate range separated from official figures. 'Cheapest' served by sorting, not by a listicle: 2026-10-03 the table gained a 'lowest published fee first' order (canonical unchanged) with a note on what cheapest does and does not mean.")
add("K","total cost of studying medicine in the UK (5–6 years, naira)","total cost of studying medicine in uk; cost of studying medicine in uk for nigerian students; how much does it cost to become a doctor in uk; cost in naira","informational","HIGH","consultancies","theukcatpeople.co.uk/post/how-much-does-it-cost-to-become-a-doctor-in-the-uk","/fees/cost-of-studying-medicine-in-the-uk","/fees/cost-of-studying-medicine-in-the-uk","/fees; /requirements/english-language; /admissions/ucat",5,"02 §C q22-25; 08 §3-4","DRAFT","Built and gated (noindex, out of sitemap) until topics student-visa, costs-2026, ucat-2026, ucas-2027 are VERIFIED in the admin queue. Naira conversion is shown as a live-rate instruction, never a fixed figure.")
add("K","living costs for medical students in the UK","living costs uk international student medicine; cost of living uk student per month","informational","MEDIUM","UKCISA, universities, generic blogs","ukcisa.org.uk; savethestudent.org","—","/fees/living-costs (later, tightly scoped)","/fees/cost-of-studying-medicine-in-the-uk",2,"register row 29; 08 §4 unsearched","RESEARCH","Research 08 §4 not yet searched; generic SERP is strong. Build only if the total-cost page's maintenance-fund facts prove insufficient and Semrush shows a Nigerian angle.")
add("K","student visa, IHS and maintenance funds for medicine","uk student visa medicine nigeria; immigration health surcharge 5 years; maintenance funds uk student visa","informational","HIGH","GOV.UK dominates","gov.uk/student-visa","/fees/cost-of-studying-medicine-in-the-uk#visa","section of the total-cost page + topic facts (student-visa)","/admissions/ucas-deadlines-2027",3,"09 visa; 08 §3","DRAFT","Lives inside the gated total-cost page; GOV.UK owns the head terms so we add only the medicine-specific layer (IHS × 5-6 years, TB test, CAS timing).")

# L — Application process (ours)
add("L","online application portal for UK medicine (Nigeria)","online application portal uk medicine; apply online uk university nigeria","transactional","MEDIUM","platforms (ApplyBoard), agents","applyboard.com; studyin-uk.com","/apply-online","/apply-online (+ /register)","/admissions/how-to-apply",3,"05 rows 3-5, 22","PUBLISHED","Our portal is the product: SMUKN-YYYY-NNNNNN applications, document checklist, approval before submission. Auth routes stay noindex.")
add("L","documents needed to apply for medicine in UK from Nigeria","documents required to study medicine in uk; waec certificate scratch card uk university; transcript uk application nigeria","informational (long-tail)","HIGH","agents","—","/admissions/how-to-apply#documents","/admissions/how-to-apply section; portal checklist","/apply-online",3,"09 documents; register row 27","PUBLISHED","Covered in-page and by the portal's document checklist; a standalone documents page only if GSC shows the query family.")

# M — Eligibility
add("M","am I eligible for UK medicine with my Nigerian qualifications (route finder)","can i get into uk medical school with waec and a levels; eligibility uk medicine nigerian degree","informational→lead","HIGH","forum only","nairaland.com","/apply-online/eligibility","/apply-online/eligibility (tool) fed by /requirements pages","/requirements/*",5,"07 rules","PUBLISHED","Instant route-category answer (standard / foundation / graduate / not yet) using published requirements; captures the lead with consent. Never says YES where a school is silent.")
add("M","switching from Arts to Medicine / non-science background","from arts to medicine uk; can i study medicine without science subjects","informational (long-tail)","MEDIUM","Nairaland thread","nairaland.com/6323922","/faq#q17","FAQ answer","/study-medicine-in-the-uk/foundation-routes; /requirements/a-levels",2,"02 §C q17","PUBLISHED","FAQ-level: the answer is 'science A-levels or a science-eligible foundation'; no page.")

# N — Interviews
add("N","medical school interviews (MMI) for international applicants / online interviews","mmi interview international students uk medicine; online interview medical school international; medicine interview nigeria","informational","MEDIUM","prep companies","themedicportal.com; medify.co","/medical-schools/{university} (interview_format facts)","/admissions/interviews (one page) once online-interview policies per school are verified","/admissions/how-to-apply",3,"register row 26; 06 interview_format (15 facts)","VALIDATED","15 interview-format facts exist; build one page when international online-interview policy is verified for ≥10 schools (QUB interviews international fee-payers online: 07). Not Nigeria-differentiated yet.")

# O — Foundation
add("O","foundation year for medicine UK international / which foundation leads to medicine","foundation year medicine uk international students; medicine foundation programme uk nigeria; which foundation leads to medicine","informational/commercial","HIGH","none; competitor snippets only","theukcatpeople.co.uk; nigeriaprivateschools.com","/study-medicine-in-the-uk/foundation-routes","/study-medicine-in-the-uk/foundation-routes","/requirements/waec; /requirements/neco; /medical-schools",5,"02 §A q26, §C q8-9; 07 foundation column; register row 18","PUBLISHED","Only routes a provider publishes as leading to Medicine (Lancashire foundation-entry MBBS, St Andrews IFM, KCL IFP, UCL UPCSE, Cardiff ISC). Everything else marked NOT PUBLISHED. Upgraded 2026-10-03 from 632 to about 1,050 words: three kinds of foundation, published statements separated from NOT PUBLISHED schools, calendar/cost/visa consequences, provider questions, two FAQs with schema.")
add("O","foundation year vs A-levels for medicine","difference between foundation year and a level uk medicine","informational (long-tail)","HIGH","Nigerian school blog","nigeriaprivateschools.com/…/168","/faq#q9","FAQ + section on foundation page","/requirements/a-levels",3,"02 §C q9","PUBLISHED","FAQ 9 plus the foundation page's comparison; no separate page.")
add("O","NCUK / pathway providers in Nigeria for UK medicine","ncuk nigeria medicine; into foundation medicine nigeria; navitas foundation medicine","commercial/navigational","MEDIUM","providers' own pages","ncuk.ac.uk; intostudy.com; navitas.com","—","provider statements as facts on the foundation page; no provider pages","/study-medicine-in-the-uk/foundation-routes",2,"07 §planned (search budget)","RESEARCH","Provider progression claims to Medicine were not retrievable in research 07; record as facts when sourced. No provider landing pages (no partnership claims).")

# P — Graduate entry
add("P","graduate entry medicine UK with a Nigerian degree","graduate entry medicine uk international students; medicine after nigerian degree uk; second degree medicine international student uk; gamsat uk international","informational","HIGH","generic PG-equivalency pages; no GEM-for-Nigerians page exists","thestudentroom.co.uk t=7524422; chester.ac.uk/international/how-to-apply/applying-for-graduate-entry-medicine/","/requirements/nigerian-degree-graduate-entry","/requirements/nigerian-degree-graduate-entry","/medical-schools?test=GAMSAT; /fees; /admissions/ucat",4,"02 §A q10, §C q31; 06 (Chester, Worcester open; Pears Cumbria home-only); 08 (Warwick, Swansea fees)","UPDATE","Unowned SERP but page is thin (317 words). Upgrading on 2026-10-03: which GEM courses accept Student-visa applicants (sourced), degree-class mapping via UK ENIC, GAMSAT vs UCAT windows, the standard-entry alternative, and the two published GEM fees.")
add("P","biomedical science / medical laboratory science UK as a route to medicine","biomedical science uk nigerian students; medical laboratory science uk for nigerians","informational (mixed with migration)","LOW","empty / jobs boards","skills-provision.com","—","section inside the graduate-entry page only","/requirements/nigerian-degree-graduate-entry",1,"02 §A q20,23; 03 verdict","REJECTED","Research 03: GEM feeder at best; HCPC/IBMS registration intent is migration, not study. One sentence on the GEM page, no page.")

# Q — GMC / registration / MDCN
add("Q","MDCN recognition of a UK medical degree (returning to Nigeria)","mdcn recognition uk medical degree; can i practise in nigeria with uk mbbs; mdcn foreign graduate assessment","informational (trust)","HIGH","empty; one competitor mention","theukcatpeople.co.uk (Nigeria guide)","/faq#q32","FAQ now; section on /working-in-the-uk when MDCN sources are verified","/working-in-the-uk",3,"02 §A q25, §C q32; 10","RESEARCH","High-value trust topic with no official source captured yet (MDCN assessment rules). Keep FAQ-level until the MDCN page is read and recorded as facts.")
add("Q","GMC registration after a UK degree (provisional registration, MLA/UKMLA)","gmc provisional registration international graduate uk; ukmla international students","informational","MEDIUM","GMC owns","gmc-uk.org","/working-in-the-uk#gmc","/working-in-the-uk section (topic facts)","/study-medicine-in-the-uk",3,"10 GMC section","DRAFT","Inside the gated working page; GMC is linked as the official source. Un-gates automatically when the topic is VERIFIED.")
add("Q","Nigerian doctor to UK (PLAB, housemanship, Nile University GMC approval)","plab for nigerian doctors; housemanship in uk nigerian graduate; nile university mbbs gmc approval","informational (different audience)","HIGH","BMA, GMC, news, forums","bma.org.uk; nairaland.com/5022863; thestudentroom.co.uk t=6990701; dailytrust.com","/faq#q34","FAQ 34 (we do not serve qualified doctors) + link-out","—",1,"02 §A q3,16, §C q34-37; register C","REJECTED","Audience is qualified doctors, outside the mission; BMA/GMC own the SERP. FAQ states the boundary and links to official sources.")

# R — Working in the UK
add("R","can I work in the UK during and after studying medicine (Graduate visa, Foundation Programme)","can i work in uk after studying medicine; graduate visa medicine uk; foundation programme international graduates uk; work 20 hours student visa","informational","HIGH","BMA owns the first page","bma.org.uk/…/studying-in-the-uk-and-your-visa","/working-in-the-uk","/working-in-the-uk","/fees/cost-of-studying-medicine-in-the-uk; /faq#q33",4,"02 §A q16, §C q33; 10; register row 25","DRAFT","Built 2026-10-03, noindex and out of the sitemap until its three topics are VERIFIED (Graduate visa 18 months from 1 Jan 2027; UKFPO prioritisation proposal in flux). Links out to GOV.UK, GMC, UKFPO, NHS England, BMA.")

# S — Long-tail questions (FAQ hub)
add("S","long-tail Nigerian questions about UK medicine (FAQ hub)","25 questions from research 02 §C: waec gcse equivalent; neco same as waec; jamb ucas; ucat slots nigeria; cost in naira; cheapest medical school; work experience nigeria; second degree medicine; recognised back in nigeria; are you an agent","informational (question)","HIGH","forum threads + competitor FAQ sections","nairaland.com; thestudentroom.co.uk; theukcatpeople.co.uk","/faq","/faq (FAQPage schema) with each answer linking into the knowledge graph; the six most Nigerian-specific also appear on the core landing page","every hub page",4,"02 §C q1-40 (29 published with sourced answers; 11 withheld)","PUBLISHED","Publish only questions with a sourced answer; 29 of the 40 are published (2026-10-03: added NECO acceptance, A-level school choice, the step-by-step process and 'is Medicine right for me', each answered from an upgraded page); 11 remain unpublished (housemanship, nursing funding, agents list, scholarships detail…) until evidence exists. Each answer links to its hub page (search-to-action chain).")
add("S","People-also-ask recovery (PAA) for the core clusters","(to be exported from Semrush Topic Research / Keyword Magic question filter)","informational","HIGH","PAA not observable via this session's search tool","—","—","answers folded into existing pages or /faq; no new URLs without evidence","—",3,"02 §E items 2, 6-7","RESEARCH","Owner action: export question-filter keywords for the 18 seeds in research 02 §E into data/semrush/lookups-YYYY-MM-DD.csv; smukn:semrush-import then updates research 02 and this register's volume/KD columns.")

# Adjacent courses (recorded under B for scope decisions)
add("B","dentistry in the UK for Nigerian students","dentistry uk nigerian students; study dentistry in uk from nigeria","informational","MEDIUM","empty Nigerian SERP","—","—","/dentistry (ONE hub page) after release 1 or if Semrush/GSC shows demand","/admissions/ucat; /fees",2,"03 verdict BUILD NOW on expertise transfer; 02 §A q15 empty SERP; register row 33a","REJECTED","Superseded 2026-10-04: subject decisions now live in cluster V (Dentistry V02 and families V40–V46), generated from data/healthcare/subjects.json. Kept so the id is never reused.")
add("B","pharmacy (MPharm) / nursing / public health for Nigerians","pharmacy uk nigerian students; nursing uk from nigeria; public health masters uk nigerian","informational (split study/migration/PG)","MEDIUM","moderate; universities, NHW, migration content","nairaland.com/5530820; studentship.com.ng","—","none until Semrush validation; public health = one FAQ answer only","—",1,"03; 02 §A q15,18-19; register rows 31-33b","REJECTED","Superseded 2026-10-04: one bundled family for three subjects contradicted the per-subject decisions in cluster V (Pharmacy V03, Nursing V04, Public Health V25). Kept so the id is never reused.")
add("B","physiotherapy / radiography UK for Nigerians","physiotherapy uk nigerian students; radiography uk nigerian students","informational","LOW","empty SERPs","—","—","none","—",1,"02 §A q15; 03 verdict DO NOT BUILD","REJECTED","Superseded 2026-10-04: per-subject decisions now live in cluster V (Physiotherapy V06, Diagnostic V08 and Therapeutic Radiography V09), which hold them at RESEARCH on 2026-10-03/04 evidence. Kept so the id is never reused.")
add("B","study medicine abroad alternatives (North Cyprus, EU) for Nigerians","study medicine in europe nigerian students; north cyprus medicine nigerian students","commercial (agents)","HIGH","agents dominate and hijack UK intent","northcypruseducation.com; medlinkstudents.com; studymedicineeurope.com","—","none","—",1,"05 rows 9-11; register C","REJECTED","Outside the mission (UK only). We do not compete for or redirect this intent.")
add("B","generic 'study in the UK' / 'life in the UK' / per-city pages / blog / news","study in uk from nigeria; life in uk for nigerian students; study medicine in london","informational (generic)","MEDIUM","generalist agents, directories","gostudyin.com; studentship.com.ng","—","none","—",1,"register C; brief 38, 91","REJECTED","Dilutes the Nigeria→UK medicine focus; per-city pages duplicate directory data; no blog or news feed.")

# V — Healthcare course universe: one row per non-flagship subject, generated from data/healthcare/subjects.json so the
# taxonomy status and the register never disagree. Medicine's own rows are clusters B–S above.
import json as _json
_tax=_json.load(open("data/healthcare/subjects.json"))["subjects"]
_map={"RESEARCH":"RESEARCH","VALIDATED":"VALIDATED","BUILD":"BUILD","DRAFT":"DRAFT","REVIEW":"REVIEW","PUBLISHED":"PUBLISHED","INDEXING":"INDEXING","MEASURING":"MEASURING","UPDATE":"UPDATE","REJECTED":"REJECTED"}
# V00 — the one hub proposed for the non-medicine subjects (research 12 §C decision): a single allied-health overview page,
# built only when §A and §B facts are recorded as reference_facts. Until then VALIDATED, no URL, not in the sitemap.
add("V","allied health and healthcare courses in the UK for Nigerian students (overview hub)","healthcare courses in uk for nigerian students; allied health courses uk international students; nhs courses for nigerians; hcpc courses uk","informational→commercial","MEDIUM","no Nigeria-specific page observed for the family; generic agent lists","idp.com; studyin-uk.com; gostudyin.com","—","/healthcare-courses (proposed; not routed)","/study-medicine-in-the-uk; /apply-online/eligibility; every V subject row",0,"docs/research/12 §A–§C; data/healthcare/subjects.json","VALIDATED","One honest overview (which professions exist, who regulates them, which sampled universities admit international students, how registration works) serves 20 RESEARCH subjects better than 20 thin pages. Builds when the §A/§B facts are verified in reference_facts.")
def _vnum(s):
    ids=[int(i[1:]) for i in s.get("decision_register_ids",[]) if i.startswith("V") and i[1:].isdigit()]
    return min(ids) if ids else None
# Ids are positional, so subjects first registered on 2026-10-03 (V02–V30) are emitted here and subjects added later are
# emitted after the families that already hold V31+ (see _subject_row calls below); an assertion keeps ids stable.
_tax_first=[s for s in _tax if not s["flagship"] and _vnum(s) is not None and _vnum(s)<=30]
_tax_later=[s for s in _tax if not s["flagship"] and s not in _tax_first]
def _subject_row(_s):
    _alts="; ".join(_s["alternative_names"])
    add("V",f"{_s['name']} in the UK for Nigerian students (subject cluster)",f"{_s['name'].lower()} uk for nigerian students; study {_s['name'].lower()} in uk from nigeria; {_alts}","informational→commercial",
        _s["nigerian_relevance"].split(" ")[0].strip(":;,") if _s["nigerian_relevance"]!="UNKNOWN" else "UNKNOWN",
        _s["competition"] if _s["competition"]!="NOT RESEARCHED" else "not yet observed",
        "—","—",
        "none until the subject reaches BUILD: then one hub page per subject (course → requirements → Nigerian qualifications → universities → fees → application → registration → career), never a section or a thin page",
        "/study-medicine-in-the-uk (healthcare courses hub, when built); /apply-online/eligibility",
        0,"data/healthcare/subjects.json; "+"; ".join(_s["sources"]) if _s["sources"] else "data/healthcare/subjects.json (not yet researched)",
        _map[_s["status"]],f"Taxonomy status {_s['status']}: {_s['status_reason']} Regulator: {_s['regulator']}.")
for _s in _tax_first: _subject_row(_s)


# V — subject long-tail families for the two VALIDATED subjects (research 12 §E, 36 SERP observations, 2026-10-03).
# Appended after the subject rows so V01–V24 keep their ids. No family has a URL: pages follow the subject's own BUILD.
_SRC="12 §E"
_NUR_HUB="/healthcare-courses/nursing (proposed; not routed) or the V01 hub"
_DEN_HUB="/healthcare-courses/dentistry (proposed; not routed) or the V01 hub"
add("V","Nursing: eligibility from a Nigerian school certificate (WAEC/NECO → BSc Adult Nursing)","waec requirements for nursing in uk university; wassce adult nursing uk entry requirements; neco nursing uk; can a nigerian study nursing in uk after secondary school; bsc nursing uk for nigerian secondary school leavers","informational","MEDIUM","one official country page (Bucks) maps WAEC/NECO grades; no result mentions WASSCE for adult nursing; the school-leaver question is captured by a North Cyprus agent and India-targeted agents","bucks.ac.uk/study/international/your-country/nigeria; northcypruseducation.com; ischoolconnect.com; aeccglobal.in","—",_NUR_HUB,"/requirements/waec; /requirements/neco; /apply-online/eligibility",3,_SRC+" N3, N9, N11, N16, N18","VALIDATED","The core study-from-WAEC intent for nursing is unanswered by any UK-focused page; it is the question the nursing node must answer once availability and entry facts are recorded per university (never inferred from Medicine).")
add("V","Nursing: how to study nursing in the UK from Nigeria (route; hijacked by nurse migration)","study nursing in uk from nigeria; nursing uk requirements for nigerian students; nursing degree uk from nigeria without nursing experience","migration (NMC, CBT/OSCE, IELTS 7) with a minority study intent","HIGH","Nigerian news and blogs (nairametrics, studentship), CV/job sites and gostudyin dominate; no UK university page; snippets quote NMCN two-year experience rules","nairametrics.com; studentship.com.ng; skills-provision.com; gostudyin.com/nigeria","—",_NUR_HUB,"/apply-online/eligibility",2,_SRC+" N1, N2, N15","RESEARCH","The SERP reads these queries as qualified-nurse migration; a study page would rank against migration content it must not imitate. Decide after Semrush `ng` shows whether a school-leaver sub-intent is measurable.")
add("V","Nursing: fees and cost for Nigerian students","how much is nursing in uk for nigerians; nursing uk fees international students","commercial / news","HIGH","Nigerian news (tuition totals, relocation anecdotes), pathway-college marketing, North Cyprus agent; no official fee table for Nigerians","guardian.ng; legit.ng; internationalcollege.cumbria.ac.uk; northcypruseducation.com","—",_NUR_HUB,"/fees",2,_SRC+" N4","RESEARCH","Only official per-university fees with a fee year may be published; §B found MMU £21,500 and aggregator figures elsewhere, all VERIFY-ON-PAGE.")
add("V","Nursing: UK universities that accept Nigerian students (university choice)","uk universities that accept nigerian students for nursing","commercial (listicle)","HIGH","Nigerian listicle blogs and IDP Nigeria; ARU Nigeria country page; news on a Hertfordshire nursing cohort","studentship.com.ng; allschool.ng; aru.ac.uk; idp.com/nigeria","—",_NUR_HUB,"/medical-schools (directory pattern)",2,_SRC+" N5","RESEARCH","Answerable only as a per-university availability list built from read official pages (courses.profession = nursing); no list may be inferred.")
add("V","Nursing: English language (IELTS) for a nursing degree","ielts score for nursing degree uk international students","informational (conflated with NMC registration IELTS)","LOW","India-targeted IELTS agents and NMC rule-change PDFs; UWS the only university","ieltsidpindia.com; specialistlanguagecourses.com; uws.ac.uk","—",_NUR_HUB,"/requirements/english-language",1,_SRC+" N6, N18","RESEARCH","Per-university IELTS differs (MMU 6.5; KCL 7.0 with 575 hours of care experience) and is never Medicine's figure; publish only as reference_facts.")
add("V","Nursing: foundation or pathway year for international students","foundation year nursing uk international students","informational / navigational","LOW","official pages dominate (BCU, Sheffield Hallam, UCAS); NCUK pathway to Huddersfield","bcu.ac.uk; shu.ac.uk; ncuk.malverninternational.com","—",_NUR_HUB,"/study-medicine-in-the-uk/foundation-routes",1,_SRC+" N7","RESEARCH","Official pages answer it; value only as a section of the nursing node, not a page.")
add("V","Nursing: application mechanics (UCAS deadline, interview, placement visa rules)","nursing uk ucas deadline international; nursing interview uk international students; nursing uk international students placement student visa","navigational / informational","LOW","fully official SERPs (UCAS, Birmingham key dates, Swansea international nursing guidance, Suffolk and Sunderland interview pages, Surrey visa hours)","ucas.com; birmingham.ac.uk; swansea.ac.uk; my.surrey.ac.uk","—",_NUR_HUB,"/admissions/how-to-apply; /admissions/ucas-deadlines-2027",1,_SRC+" N8, N10, N17","RESEARCH","Official sources already answer; a section linking to them, never a competing page.")
add("V","Nursing: scholarships for Nigerian students","nursing scholarship uk nigerian students undergraduate","informational / commercial","HIGH","Nigerian scholarship blogs; official Southampton and Stirling awards","o3schools.com; studentship.com.ng; southampton.ac.uk","—",_NUR_HUB,"/fees",1,_SRC+" N13","RESEARCH","Only named official awards with their published conditions may be listed (Southampton Global Talent in Adult Nursing seen; VERIFY-ON-PAGE).")
add("V","Nursing: forum demand (Nairaland) and generic study-abroad agents","nairaland study nursing uk; study nursing abroad from nigeria","migration / commercial-agent","HIGH","Nairaland threads are HCA-visa and OSCE routes; multi-country agents and US outbound pages","nairaland.com; dofmar.com; emonovo.com","—","none","—",1,_SRC+" N12, N14","REJECTED","Migration and multi-country intents are outside the mission (UK undergraduate study); recorded so the pattern is not re-litigated.")
add("V","Dentistry: eligibility from a Nigerian school certificate (WAEC/NECO → BDS)","waec requirements for dentistry in uk university; wassce dentistry uk entry requirements; neco dentistry uk; can a nigerian study dentistry in uk after secondary school","informational","MEDIUM","no result in any query mentions WAEC, WASSCE or NECO for BDS; UK prep sites give generic AAA/IB advice; the school-leaver question surfaces Nigerian academic papers and one agent","uniadmissions.co.uk; themedicportal.com; londondentalinstitute.com; gostudyin.com/nigeria","—",_DEN_HUB,"/requirements/waec; /admissions/ucat; /apply-online/eligibility",3,_SRC+" D2, D3, D9, D11, D18","VALIDATED","Zero Nigeria-specific content exists for the core dentistry intent; the dentistry node answers it per school (Manchester, Cardiff, KCL, Aberdeen facts from §B/§E), never from Medicine's statements.")
add("V","Dentistry: how to study dentistry in the UK from Nigeria (route)","study dentistry in uk from nigeria; dentistry uk requirements for nigerian students; bds uk nigerian students","commercial-agent plus dentist job-seeking","MEDIUM","gostudyin Nigeria page, dentist CV pages, Nigerian news; Bristol Nigeria leaflet and generic country pages (Birmingham, Canterbury)","gostudyin.com/nigeria; skills-provision.com; leadership.ng; bristol.ac.uk Nigeria leaflet","—",_DEN_HUB,"/study-medicine-in-the-uk/from-nigeria",2,_SRC+" D1, D5, D17","RESEARCH","Served by the dentistry node once built; the only Nigeria-specific competitor is an agent page.")
add("V","Dentistry: fees and international places","dentistry uk fees for international students bds; dentistry uk international places","informational / commercial","LOW","official fee pages (Manchester, UCLan) and a prep-site international guide; no official statement of international places except Manchester's statistics page (§B)","manchester.ac.uk; uclan.ac.uk; theukcatpeople.co.uk; idp.com","—",_DEN_HUB,"/fees",2,_SRC+" D4, D16; 12 §B","RESEARCH","Per-school fees and places exist officially (Manchester £36,500 year 1, about 15 international places); publish only as reference_facts per school.")
add("V","Dentistry: UCAT for Nigerian dentistry applicants","ucat dentistry nigeria; ucat test centre nigeria dentistry","informational","HIGH","two UK prep sites hold Nigeria-specific UCAT guides (for Medicine); dental school UCAT pages (Aberdeen, Manchester, Glasgow) are not Nigeria-specific; no official UCAT page surfaced","leadingtuition.co.uk; theukcatpeople.co.uk; abdn.ac.uk; bmh.manchester.ac.uk","—","/admissions/ucat (a dentistry section on the existing UCAT page, not a new page)","/admissions/ucat",2,_SRC+" D15","VALIDATED","Upgrade before multiplying: the live UCAT page already serves Nigerian UCAT intent; adding which dental schools use the UCAT needs those schools' pages read and recorded as facts first.")
add("V","Dentistry: English language, foundation (IFP) and application mechanics","ielts for dentistry uk bds; foundation year dentistry uk international; dentistry uk ucas deadline international 15 october; dentistry interview uk international mmi","informational / navigational","LOW","official pages dominate (Bristol IFP for Dentistry, Aberdeen BDS IELTS 7.0, QUB admissions policy, UCAS October deadline, Manchester and Birmingham interview pages); prep-site MMI guides","bristol.ac.uk; abdn.ac.uk; qub.ac.uk; ucas.com; bluepeanut.com","—",_DEN_HUB,"/admissions/ucas-deadlines-2027; /admissions/how-to-apply",1,_SRC+" D6, D7, D8, D10","RESEARCH","Official sources answer; sections of the dentistry node link to them. Bristol IFP guarantees a BDS interview (FACT, VERIFY-ON-PAGE).")
add("V","Dentistry: scholarships for Nigerian students","dentistry scholarship uk nigerian students undergraduate bds","informational","MEDIUM","Birmingham's Nigeria scholarship page excludes BDS; other awards are UK-resident or widening-participation","birmingham.ac.uk; topuniversities.com; mastersportal.com","—",_DEN_HUB,"/fees",1,_SRC+" D13","RESEARCH","The honest answer is largely negative (BDS excluded from the one Nigeria award seen); record as a fact, not a page.")
add("V","Dentistry: forum demand and generic study-abroad agents","nairaland dentistry uk study; study dentistry abroad from nigeria","dentist migration / human interest","LOW","no Nairaland dentistry thread surfaced; Canada and US advanced-standing programmes for qualified dentists dominate; UK absent","idp.com; utoronto.ca; rutgers.edu; emonovo.com","—","none","—",1,_SRC+" D12, D14","REJECTED","Qualified-dentist migration and multi-country intents are outside the mission.")


# V — subjects added to the taxonomy after 2026-10-03 (ids continue after V46).
for _s in _tax_later: _subject_row(_s)

# V — allied-health long-tail families (research 12 §F, 49 observations, 2026-10-04). No URL until the subject reaches BUILD.
_F="12 §F"
add("V","Pharmacy: WAEC/NECO and entry requirements for MPharm from Nigeria","mpharm uk requirements for nigerian students waec; uk universities that accept waec for pharmacy; can a nigerian study pharmacy in uk","informational","MEDIUM","no official page with WAEC wording for MPharm; aggregators (unienrol, universitydb /from/nigeria) and a medicine prep site fill the slot; 'WAEC' pulls in Nigerian university pages","unienrol.com; universitydb.io; gostudyin.com/nigeria; theukcatpeople.co.uk","—","/healthcare-courses/pharmacy (proposed; not routed)","/requirements/waec; /apply-online/eligibility",3,_F+" P2, P6, P8, P12","VALIDATED","The pharmacy node's first job: a per-university answer to WAEC/NECO → MPharm, built from read official pages (Manchester, UCL, Nottingham, Cardiff), never from Medicine's statements.")
add("V","Pharmacy: fees, foundation year and the training year after the degree","pharmacy uk fees for international students 2026; mpharm with foundation year international students; mpharm international students foundation training year visa","informational","LOW","official university pages dominate (Kent, Sunderland, Manchester, UCL, Brighton)","kent.ac.uk; sunderland.ac.uk; manchester.ac.uk; ucl.ac.uk","—","/healthcare-courses/pharmacy (sections)","/fees",2,_F+" P3, P7, P9","RESEARCH","Official pages answer; sections of the pharmacy node with per-university facts, not separate pages.")
add("V","Pharmacy: is it worth it / parent questions about MPharm for a Nigerian child","is it worth studying pharmacy in uk as a nigerian; my son wants to study pharmacy in uk","commercial (parent)","MEDIUM","answered only by agents (gostudyin /nigeria/, yocket, idp)","gostudyin.com/nigeria; yocket.com; idp.com","—","/healthcare-courses/pharmacy (FAQ)","/apply-online/eligibility",1,_F+" P10","RESEARCH","A decision question for the node's FAQ once facts exist; no page of its own.")
add("V","Pharmacy: qualified Nigerian pharmacist to the UK (OSPAP, GPhC)","nigerian pharmacist uk ospap gphc registration; b.pharm nigeria to uk pharmacist how","migration (qualified professionals)","HIGH","OSPAP stories, registration-prep competitors (iatrox), news on OSPAP demand from Nigeria","iatrox.com; pharmaceutical-journal.com; blogs.brighton.ac.uk","—","none","—",1,_F+" P4, P11","REJECTED","Qualified-professional migration is outside the mission (undergraduate study). Recorded so the pattern is not re-litigated; the pharmacy node must say it does not cover OSPAP.")
add("V","Midwifery: can international students study midwifery in the UK (eligibility)","can international students study midwifery in uk; midwifery uk home students only; study midwifery in uk from nigeria","informational","LOW","aggregators say 'yes' while Cardiff, Cumbria, Manchester and UCAS listings say closed to international fee status","studee.com; hotcoursesabroad.com; cardiff.ac.uk; cumbria.ac.uk","—","/healthcare-courses (overview hub, availability section)","/apply-online/eligibility",2,_F+" M1, M2, M6, M8","RESEARCH","The honest answer is 'closed at most universities checked'; it belongs in the overview hub's availability table, not a midwifery page that would mostly say no.")
add("V","Midwifery: fees and parent cost questions","bsc midwifery uk fees international students; my daughter wants to study midwifery in uk from nigeria how much","informational","LOW","fee lists from aggregators and university fee pages; no result warns that several universities are home-only","studee.com; ljmu.ac.uk; york.ac.uk","—","none until availability is mapped","—",1,_F+" M3, M9","RESEARCH","Publishing fees without the home-only caveat would mislead; availability first.")
add("V","Midwifery: qualified Nigerian midwife to the UK (NMC CBT/OSCE)","nigerian midwife nmc registration uk cbt osce","migration (qualified professionals)","HIGH","Nigerian news on a CBT-centre investigation, job and emigration sites; NMC statement","nmc.org.uk; studentship.com.ng; wheretoemigrate.io","—","none","—",1,_F+" M5","REJECTED","Qualified-professional migration is outside the mission.")
add("V","Physiotherapy: study from Nigeria / which UK universities accept Nigerian students","study physiotherapy in uk from nigeria; uk universities that accept nigerian students for physiotherapy; physiotherapy uk requirements for nigerian students waec","informational / commercial","MEDIUM","a Nigeria-targeted agent and Nigerian domestic admissions content (JAMB, BUK, UNIBEN); no UK university page","gostudyin.com/nigeria; myeduvantage; myschool.ng","—","/healthcare-courses (overview hub) until physiotherapy reaches BUILD","/requirements/waec; /apply-online/eligibility",2,_F+" PH1, PH3, PH7","RESEARCH","Demand exists but the SERP reads it as Nigerian domestic admissions; per-university availability (Brunel uses private placements; some courses are UK-fee only) must be mapped first.")
add("V","Physiotherapy: fees, entry and placements for international students","bsc physiotherapy uk international students fees entry requirements; can international students study physiotherapy in the uk placement; physiotherapy with foundation year international","informational","LOW","official pages dominate (Brunel, Sheffield Hallam, UCAS)","brunel.ac.uk; shu.ac.uk; ucas.com","—","/healthcare-courses (overview hub, availability section)","/fees",1,_F+" PH2, PH5, PH8, PH9","RESEARCH","Official pages answer; record per-university facts.")
add("V","Physiotherapy: qualified Nigerian physiotherapist to the UK (HCPC)","nigerian physiotherapist hcpc registration uk; nairaland physiotherapy uk","migration (qualified professionals)","HIGH","CV listings, a migration podcast, registration guides; no HCPC page surfaced","skills-provision.com; player.fm; surreyphysio.co.uk","—","none","—",1,_F+" PH4, PH6","REJECTED","Qualified-professional migration is outside the mission.")
add("V","Radiography: can international students study radiography in the UK (diagnostic and therapeutic)","can international students study radiography in uk; diagnostic radiography international nhs placement; therapeutic radiography bsc international applicants","informational","LOW","agents say 'yes' without the caveat; UCAS and Cardiff say several courses are UK-fee only; Liverpool therapeutic takes international applicants","careerwidth; aeccglobal; idp.com; ucas.com; liverpool.ac.uk","—","/healthcare-courses (overview hub, availability section)","/apply-online/eligibility",2,_F+" R3, R4, R8","RESEARCH","Availability is provider-specific and often closed; the overview hub's availability table answers it honestly.")
add("V","Radiography: entry requirements with WAEC and fees","radiography uk entry requirements waec nigeria international; diagnostic radiography bsc uk international students fees","informational","MEDIUM","four UK university Nigeria country pages with generic WAEC rules (the most official SERP in the sweep); fee pages","londonmet.ac.uk; brookes.ac.uk; abdn.ac.uk; kingston.ac.uk; keele.ac.uk","—","/healthcare-courses (overview hub)","/requirements/waec",1,_F+" R2, R6","RESEARCH","Generic WAEC rules are university-level and already shape our WAEC page; radiography-specific statements not found.")
add("V","Radiography: study from Nigeria / qualified radiographer to the UK (HCPC)","study radiography in uk from nigeria; nigerian radiographer hcpc registration uk; is radiography a good course to study in uk for nigerian student","migration / Nigerian domestic","HIGH","qualified-radiographer CVs, a Society of Radiographers profile, Nigerian domestic radiography blogs","skills-provision.com; society-of-radiographers; medicalmirror.org","—","none","—",1,_F+" R1, R5, R7","REJECTED","The SERP reads these as migration or Nigerian domestic study; outside the mission.")
add("V","Biomedical science: is Nigerian medical laboratory science the same as UK biomedical science","is medical laboratory science the same as biomedical science in uk; study medical laboratory science in uk from nigeria","informational","HIGH","the MLS term returns only CVs and migration content; the mapping appears on Wikipedia, an NHS NI careers PDF and the British Council subject page; no official page maps MLS to an IBMS-accredited BSc for students","skills-provision.com; wikipedia.org; britishcouncil.org","—","/healthcare-courses (overview hub) and the graduate-entry page section on biomedical science","/requirements/nigerian-degree-graduate-entry",3,_F+" B1, B6; 12 §G","VALIDATED","A real terminology gap for Nigerian readers: explain that the UK term is biomedical science, that registration runs through an IBMS-accredited degree and portfolio, and that an MLS degree is assessed case by case (IBMS facts, VERIFY-ON-PAGE). Never state equivalence.")
add("V","Biomedical science: study from Nigeria, WAEC, fees and IBMS-accredited degrees","study biomedical science in uk from nigeria requirements; biomedical science uk waec accepted nigeria; biomedical science ibms accredited bsc uk international students fees; biomedical science with foundation year international","informational","MEDIUM","official university pages and Nigeria country pages (generic WAEC: SSCE alone not enough, foundation or A-levels first); fee pages","shu.ac.uk; brookes.ac.uk; lsbu.ac.uk; westminster.ac.uk","—","/healthcare-courses (overview hub)","/requirements/waec; /fees",2,_F+" B2, B5, B7, B9, B10","RESEARCH","Official pages answer; per-university facts first.")
add("V","Biomedical science: qualified Nigerian medical laboratory scientist to the UK (IBMS, HCPC)","nigerian medical laboratory scientist hcpc ibms certificate of competence uk; nairaland medical laboratory science uk","migration (qualified professionals)","HIGH","IBMS pages lead; Nigerian blogs, CVs and a 2020 Nairaland migration post","ibms.org; profolio.ng; nairaland.com","—","none","—",1,_F+" B3, B4","REJECTED","Qualified-professional migration is outside the mission.")

# Medicine long-tail families (research 13, 45 observations, 2026-10-04). Cluster letters follow the existing scheme.
_M="13"
add("G","JUPEB, IJMB, OND/HND and other Nigerian post-secondary qualifications for UK medicine","does uk medical school accept jupeb or ijmb for medicine; study medicine in uk with ond or hnd nigeria; can i study medicine in uk after jamb","informational","HIGH","only Nigerian direct-entry content, an Indian aggregator and spam; no UK-focused answer; one blog implies OND/HND may give direct entry","schoolings.org; translayte.com; careers360.com","/faq#q6","/requirements/waec (one section: what each school publishes about Nigerian post-secondary qualifications)","/requirements; /study-medicine-in-the-uk/foundation-routes; /faq",4,_M+" q6, q12, q15, q17, q36","PUBLISHED","Answered now at FAQ level (question 6 widened from JAMB to JUPEB, IJMB, OND and HND) with the honest default: no school we found publishes them as an entry qualification for Medicine. A WAEC-page section follows only when per-school statements are recorded as facts.")
add("J","is UK medicine free / funding for Nigerian undergraduates","is medicine in uk free for nigerian students; scholarship to study medicine in uk for nigerian undergraduate students","informational / funding","HIGH","Nigerian scholarship blogs claim free or fully funded study; Birmingham's Nigeria scholarship explicitly excludes MBChB and BDS (FACT, VERIFY-ON-PAGE)","excelsiorscholarships.com; studentship.com.ng; birmingham.ac.uk","/faq#q28","/faq (one answer) and the fee guide's funding note","/fees",3,_M+" q3, q18, q19","PUBLISHED","Answered at FAQ level (question 28 now opens with the \"is it free\" wording) and backed by the costs-2026 funding fact on the total-cost page; J02 (a scholarships page) stays rejected.")
add("D","new and international-only UK medical schools (2026–2027 intakes)","new uk medical schools 2027 international students; medical schools that only take international students","informational / commercial","MEDIUM","Times Higher Education news and prep sites; MSC news item; no consolidated official list","timeshighereducation.com; medschools.ac.uk; nextgenmedprep.com","/medical-schools","/medical-schools (directory records for each new school)","/study-medicine-in-the-uk/from-nigeria",3,_M+" q45","VALIDATED","Directly commercial for international applicants; add directory records only from each school's own page (names reported in news are not facts).")
add("K","cheapest UK medical school for international students","cheapest medical school in uk for international students; cheapest way to study medicine in uk from nigeria","commercial","MEDIUM","prep-site and aggregator lists that contradict each other (one school named cheapest and home-only)","theukcatpeople.co.uk; gostudyin.com; bluepeanut.com","/fees","/fees (the lowest-fee ordering, canonical /fees)","/medical-schools",3,_M+" q7, q33","PUBLISHED","The fee guide's lowest-fee order answers it from published, sourced fees and shows home-only schools as such; no separate page.")
add("M","age: minimum and maximum age for UK medicine, mature applicants","age limit for medicine in uk international students; can i study medicine in the uk at 25 or 30","informational","MEDIUM","prep sites with dedicated minimum-age pages; UCAS and BMA for mature applicants; no university page ranks","themedicportal.com; uniadmissions.co.uk; ucas.com; bma.org.uk","/faq","/faq (one answer)","/apply-online/eligibility",2,_M+" q4, q27","RESEARCH","FAQ-level; minimum ages differ by school and need school statements before any list is published.")
add("S","course length: how many years is medicine in the UK","how many years is medicine in uk for nigerian students; how long is medical school in uk","informational","HIGH","a North Cyprus agent ranks first; Nigerian news on a domestic course-length debate; wrong lengths in news (four years)","northcypruseducation.com; guardian.ng; thewillnews.com","/faq#q41","/study-medicine-in-the-uk (route lengths) and one FAQ answer","/faq",3,_M+" q1, q15, q38","PUBLISHED","New FAQ answer 41 states the route lengths the pillar already explains and corrects the \"four years\" figure seen in news; links to the pillar.")
add("P","nursing or another health degree from Nigeria to UK medicine","study medicine in uk after nursing degree nigeria","informational","MEDIUM","the SERP drifts to nurse migration","nairametrics.com; gostudyin.com","/requirements/nigerian-degree-graduate-entry","/requirements/nigerian-degree-graduate-entry (section)","/faq",2,_M+" q13","RESEARCH","Belongs inside the graduate-entry page; needs school statements on accepted first degrees.")
add("Q","UK degree taught outside the UK (Malta, Malaysia, a planned Lagos campus) and UK-graduate status","queen mary malta medicine; uk university campus in nigeria medicine degree; study medicine uk degree outside uk","informational / compare","HIGH","Nigerian government and news on a planned Coventry Lagos campus (no UK university page found); QMUL Malta pages; the 2026 prioritisation law","leadership.ng; fmino.gov.ng; qmul.ac.uk; legislation.gov.uk","/working-in-the-uk#prioritisation","/working-in-the-uk#prioritisation (gated) and one FAQ answer","/medical-schools",3,_M+" q25, q26, q33, q34, q37, q40","DRAFT","Material to Nigerian families comparing offers: where the training happens decides UK-graduate priority under the Act's definition (prioritisation_act, VERIFY-ON-PAGE). Explained on the gated working page; the planned Lagos campus is not presented until a UK university source exists.")
add("C","transfer from a Nigerian medical school to a UK medical school","transfer from nigerian medical school to uk medical school","informational","MEDIUM","a generic Nigerian transfer blog only; nothing official","studentship.com.ng; legit.ng","—","/faq (one answer) once school statements exist","/apply-online/eligibility",1,_M+" q20","RESEARCH","No official statements found; the default answer (apply as a new applicant) must be confirmed per school before it is published.")
add("B","recognition of a UK medical degree in the USA or Canada","is uk medical degree recognised in usa canada nigerian student","informational","LOW","Nigerian news on a Nigerian university's GMC status dominates","dailytrust.com; honoris.net","—","none","—",0,_M+" q31","REJECTED","Registration outside the UK and Nigeria is outside the mission and outside our verification scope.")
add("E","US-curriculum applicants (SAT, AP) for UK medicine","study medicine in uk with sat scores international","informational","LOW","prep sites; no official page ranks","themedicportal.com; leadingtuition.co.uk","—","none until demand is shown","/requirements",1,_M+" q14","RESEARCH","A minority route for Nigerian students; revisit with Semrush ng data.")
add("E","where to take A-levels in Nigeria / predicted grades from Nigerian schools","study medicine in uk with cambridge a level from nigerian school","local / informational","MEDIUM","Nigerian school directories and news","nigeriaprivateschools.com; abbeycolleges.co.uk","—","none","/requirements/a-levels",0,_M+" q36","REJECTED","A directory of Nigerian schools is unverifiable and not our service; the A-levels page covers what UK schools require.")
add("I","January intake and private UK medical schools","uk medical school january intake international students","informational","LOW","Buckingham FAQ; stale 2014–15 fee news","buckingham.ac.uk; mddus.com","/medical-schools","/medical-schools (the school's record)","/admissions/ucas-deadlines-2027",1,_M+" q23","RESEARCH","FAQ-level inside the school's directory record; stale fees in the SERP must never be repeated.")

# Trust / legal (navigational, required in the register because every sitemap URL needs a row)
for path,name in [("/","Home"),("/about","About"),("/contact","Contact"),("/how-we-verify","How we verify (editorial and verification policy)"),("/privacy","Privacy notice"),("/terms","Terms of use"),("/application-terms","Application terms"),("/refund-policy","Refund policy")]:
    add("T",f"{name} (navigational / trust)",f"studymedicineuknigeria {name.lower()}","navigational","—","—","—",path,path,"—",0 if path!="/" else 5,"register row 23 (row 1 for home)","PUBLISHED","Trust or navigational page; not a keyword target. Home is the journey entry and links to every hub and to the core landing page." if path=="/" else "Trust page required by the asset register (row 23); carries no keyword target and no FAQ schema.")

# Derived columns requested by the owner's register schema (subject, internal-link role, conversion role, indexation
# decision). Deterministic from the row itself, so they never carry a judgement that is not already in the status/URL.
LIVE={"PUBLISHED","INDEXING","MEASURING","UPDATE"}
HUBS={"/study-medicine-in-the-uk","/requirements","/fees","/admissions","/medical-schools","/faq","/apply-online"}
_subject_by_family={f"{_s['name']} in the UK for Nigerian students (subject cluster)":_s["slug"] for _s in _tax}
for r in rows:
    url=r["current_url"]
    if r["cluster"]=="V": r["subject"]=_subject_by_family.get(r["query_family"],"allied-health (all non-medicine subjects)")
    elif r["cluster"]=="T": r["subject"]="site"
    else: r["subject"]="medicine"
    if url=="—": r["indexation_decision"]="none (no URL)" if r["status"]!="REJECTED" else "none (rejected)"
    elif "#" in url: r["indexation_decision"]="anchor on an indexed page"
    elif "?" in url: r["indexation_decision"]="noindex (filter view)"
    elif "{" in url: r["indexation_decision"]="index (one URL per record)"
    elif r["status"]=="DRAFT": r["indexation_decision"]="noindex until the gated facts are verified"
    elif r["status"] in LIVE: r["indexation_decision"]="index"
    else: r["indexation_decision"]="none (not built)"
    base=url.split("#")[0].split("?")[0]
    if url=="—": r["internal_link_role"]="none yet"
    elif url=="/": r["internal_link_role"]="entry (links to every hub and the core landing page)"
    elif url=="/study-medicine-in-the-uk/from-nigeria": r["internal_link_role"]="primary landing (linked from home, every hub and the FAQ)"
    elif r["cluster"]=="T": r["internal_link_role"]="footer / trust"
    elif "#" in url: r["internal_link_role"]="FAQ anchor (linked from the related spoke)"
    elif base in HUBS: r["internal_link_role"]="hub (links down to its spokes and across to eligibility)"
    else: r["internal_link_role"]="spoke (linked from its hub; links to eligibility and Apply Online)"
    if r["cluster"]=="A": r["conversion_role"]="conversion (service, eligibility or trust step)"
    elif r["cluster"]=="T": r["conversion_role"]="trust"
    elif url=="—": r["conversion_role"]="—"
    else: r["conversion_role"]="search-to-action (in-body link to the eligibility check or Apply Online; tested)"
# Stability: a subject's recorded subject-cluster id must still match what the builder generates.
for _s in _tax:
    if _s["flagship"]: continue
    _row=next(r for r in rows if r["query_family"]==f"{_s['name']} in the UK for Nigerian students (subject cluster)")
    _rec=[i for i in _s.get("decision_register_ids",[]) if i.startswith("V") and _vnum(_s) is not None and int(i[1:])==_vnum(_s)]
    assert not _rec or _rec[0]==_row["id"] or _s in _tax_later, f"{_s['slug']}: recorded {_rec} but generated {_row['id']}"
with open("data/seo/decision-register.csv","w",newline="") as f:
    w=csv.DictWriter(f,fieldnames=list(rows[0].keys()),lineterminator="\n")
    w.writeheader(); w.writerows(rows)
from collections import Counter
print(len(rows),"rows"); print(Counter(r["status"] for r in rows)); print(sorted({r["current_url"] for r in rows if r["status"]=="PUBLISHED"}))
