"""Regenerates data/seo/decision-register.csv from the rows declared below (one call per query family).
Run from the repository root: python3 ops/seo/build-register.py. Edit rows here, never the CSV by hand; the
Semrush importer may fill volume/keyword_difficulty cells in the CSV, so re-run the importer after regenerating."""
import csv
NA="DATA UNAVAILABLE (Semrush: no API units; owner lookup pending)"
D="2026-10-03"
rows=[]
def add(cluster,family,examples,intent,relevance,serp,competing,current,recommended,supporting,score,sources,status,reason,review="2027-01-15",db="ng"):
    rows.append(dict(id=f"{cluster}{sum(1 for r in rows if r['cluster']==cluster)+1:02d}",cluster=cluster,query_family=family,example_queries=examples,intent=intent,country_db=db,nigerian_relevance=relevance,volume=NA,keyword_difficulty=NA,serp_features_observed=serp,competing_urls=competing,current_url=current,recommended_page=recommended,supporting_pages=supporting,relevance_score=score,sources=sources,status=status,status_reason=reason,decided_on=D,review_due=review))

# A — Commercial (our service)
add("A","apply online for UK medicine from Nigeria / medicine application help Nigeria","apply to study medicine in uk from nigeria; uk medicine application help nigeria; medical school application service nigeria","commercial/transactional","HIGH","agents, North Cyprus intent hijack; no UK-medicine-only service page observed","northcypruseducation.com; studyin-uk.com; ukeas.com","/apply-online","/apply-online","/apply-online/services; /apply-online/eligibility; /admissions/how-to-apply",5,"02 §A q1-4; 05 table; 11 terminology","PUBLISHED","Gateway page is the principal CTA target of every landing page; prices shown only once set by the owner (no fabricated fees).")
add("A","UK medicine application service prices / consultant fees","medicine admissions consultant fee; uk university application agent cost nigeria","commercial","MEDIUM","competitors hide prices (05)","theukcatpeople.co.uk; medicmind.co.uk","/apply-online/services","/apply-online/services","/apply-online; /refund-policy; /application-terms",4,"05 §prices","PUBLISHED","Deliverables are published; prices appear only when the owner sets service tiers in the admin. Transparent pricing is the differentiator competitors lack.")
add("A","eligibility check for UK medicine (Nigerian qualifications)","am i eligible to study medicine in uk; check eligibility medicine uk waec","lead capture","HIGH","none (tools do not rank; captured via landing pages)","—","/apply-online/eligibility","/apply-online/eligibility","/requirements; /requirements/waec; /study-medicine-in-the-uk/foundation-routes",5,"07 rules","PUBLISHED","Conversion tool, not a search target; every informational page links to it as the next step. Noindex not required: it has unique explanatory copy and a FAQ-free answer.")
add("A","are you an agent / official representative of UK universities","uk university agents in nigeria; official representative university nigeria","navigational/trust","HIGH","studentship.com.ng agent list; university 'find a representative' pages","studentship.com.ng/uk-universities-agents-nigeria/","/our-status","/our-status","/about; /how-we-verify; /faq#q40",4,"11 terminology; 02 §C q40","PUBLISHED","We never claim official agent status; the page states exactly what we are and are not. Supports trust, not traffic. Upgraded 2026-10-03 from 306 to about 850 words: the sector vocabulary (agent, representative, referral partner, sub-agent, counsellor, UCAS registered centre, British Council training) with our position on each, a four-step check anyone can run on any service, FAQ 40 with schema.")

# B — Medicine (study medicine in the UK, general)
add("B","study medicine in the UK (international, generic)","study medicine in uk; how to study medicine in the uk; mbbs in uk for international students","informational","MEDIUM","strong UK prep companies (themedicportal, medify), universities, UCAS","themedicportal.com; medify.co; ucas.com","/study-medicine-in-the-uk","/study-medicine-in-the-uk","/study-medicine-in-the-uk/from-nigeria; /medical-schools; /requirements; /fees",3,"02 §A q1-3","PUBLISHED","Pillar page. Generic head term is UK-competitor dominated; we hold it only as the parent of the Nigerian landing page and do not chase it with volume content. Upgraded 2026-10-03 from 598 to about 1,250 words: what the degree is, three routes, where international students can go (live counts), the calendar, cost, after graduation with GMC facts, an honest decision section and three FAQs with schema.")
add("B","why study medicine in the UK / is UK medicine right for me","is medicine the right course to study in the uk; why study medicine in uk","informational","MEDIUM","Nairaland thread; agent blogs","nairaland.com/8665379","—","/study-medicine-in-the-uk (section) — no separate page","/working-in-the-uk; /fees/cost-of-studying-medicine-in-the-uk",2,"02 §A q17; register row 24","RESEARCH","Register row 24: fact-led content depends on research 10 gaps (MLA, Foundation Programme prioritisation policy in flux). Re-decide with Semrush ng/uk volumes; if built, one page maximum.")
add("B","MBBS UK for Nigerian students (ambiguous)","mbbs uk nigerian students; mbbs in uk from nigeria","informational (ambiguous: study vs Nile/GMC news)","HIGH","Nile University GMC-approval news cluster dominates","honoris.net; dailytrust.com; globaladmissions.com","/study-medicine-in-the-uk/from-nigeria","/study-medicine-in-the-uk/from-nigeria (disambiguation paragraph)","/faq",3,"02 §A q3","UPDATE","Core landing already covers it; add an explicit 'MBBS vs MBChB/MBBS naming' disambiguation sentence and link the FAQ on Nigerian MBBS recognition. No separate page: intent splits and the news intent is not ours.")

# C — Nigerian-specific core
add("C","study medicine in the UK from Nigeria (core)","study medicine in uk from nigeria; medicine in uk for nigerian students; how to study medicine in uk from nigeria","informational→commercial","HIGH","1 consultancy landing (theukcatpeople), news, listicles, North Cyprus agent; no official source ranks","theukcatpeople.co.uk/application-guide/ucas/study-medicine-in-the-uk-from-nigeria; leadingtuition.co.uk/blog/ucat-nigerian-students-uk-medicine; northcypruseducation.com","/study-medicine-in-the-uk/from-nigeria","/study-medicine-in-the-uk/from-nigeria","/requirements/waec; /admissions/ucat; /fees; /medical-schools; /apply-online",5,"02 §A q1-4, §D; 05 ranks 1-3","PUBLISHED","Primary asset. Internal-link audit (2026-10-03) found only one in-body link to it from other pages: fixed by adding contextual links from the home page, hubs and FAQ (see DECISION-ENGINE.md §6).")
add("C","medical universities in UK for Nigerians / UK medical school Nigeria (list intent)","medical universities in uk for nigerian students; uk medical schools for nigerians; best uk universities for medicine for nigerians","informational/commercial (list)","HIGH","unsourced blog lists; scholarship listicles","studentship.com.ng; twinkl.pt; excelsiorscholarships.com","/medical-schools","/medical-schools (filter: accepts international) + Nigerian-applicant block on each university page","/study-medicine-in-the-uk/from-nigeria; /requirements/waec",5,"02 §A q4; 06","PUBLISHED","Served by the directory with per-school published statements rather than a 'best for Nigerians' list (rankings REJECTED, see S/REJECTED rows).")
add("C","Nigerian student stories / news about admission to UK medicine","nigerian girl offered admission medicine uk","news/navigational","LOW","Nigerian news sites","icirnigeria.org; dailytrust.com","—","none","—",1,"02 §A q2","REJECTED","News intent; we publish no testimonials or student stories (owner rule: no fabricated or unverifiable social proof).")

# D — UK medical schools (directory)
add("D","UK medical schools that accept international students","uk medical schools that accept international students; which uk universities accept international medicine students; how many international places medicine uk","informational/commercial","HIGH","strong: prep companies, THE; no Nigeria angle","nextgenmedprep.com/medical-schools/international-students; bluepeanut.com; timeshighereducation.com","/medical-schools","/medical-schools","/medical-schools/{university}; /fees; /admissions/ucat",5,"02 §A q14, §C q26-27; 06","PUBLISHED","Directory with international_policy, places, test, route and verification dates. Filter combinations stay query-string + canonical to the directory until GSC shows demand (row D03).")
add("D","individual UK medical school for international / Nigerian applicants","{university} medicine international entry requirements; {university} nigeria entry requirements medicine","informational","HIGH","universities' own country pages rank (Aberdeen, Manchester, Cardiff, Edinburgh)","abdn.ac.uk; manchester.ac.uk; cardiff.ac.uk; ed.ac.uk","/medical-schools/{university}","/medical-schools/{university} (only schools open to international applicants with ≥3 verified fields are indexable)","/requirements/waec; /fees; /admissions/ucat",4,"02 §A q5; 06; 07","PUBLISHED","University pages are indexable only when they carry a Nigerian-applicant block with published statements; home-only schools are listed in the directory and are noindex. Prevents thin university pages. 2026-10-03: every record now adds a computed 'what this means if you are applying from Nigeria' section (policy, places, WAEC/NECO, English, foundation, graduate entry, each switching on whether a fact is published) and 'how to apply to this school' (route, test, UCAS deadline and UCAT window facts), plus Course schema with an Offer only for a VERIFIED fee; 550–700 words before staff verification.")
add("D","whitelisted directory filters (no UCAT / accepting international / GAMSAT)","uk medical schools without ucat; medical schools uk no ucat international; gamsat medical schools uk international","informational/commercial","MEDIUM","prep company listicles","themedicportal.com; medify.co","/medical-schools?test=… (canonical → /medical-schools)","static filter URLs only if Semrush ng/uk or GSC confirms demand","/admissions/ucat; /requirements/nigerian-degree-graduate-entry",3,"register row 30; 18.1","RESEARCH","Needs Semrush or GSC evidence before creating indexable filter pages; otherwise they stay noindex query strings. Owner lookup: 'uk medical schools no ucat' (uk, ng).")
add("D","compare medical schools","compare uk medical schools international fees","tool","MEDIUM","—","—","—","/medical-schools/compare (noindex tool)","/medical-schools",2,"register row 28","VALIDATED","Build when ≥20 schools have fee + test + route + deadline verified; it will be a noindex tool, not a landing page.")
add("D","best / top medical schools in the UK (for Nigerians)","best medical schools in uk; top uk medical schools for nigerian students; ranking medical schools uk","commercial (list)","MEDIUM","rankings sites, Nairaland","nairaland.com/7408807; timeshighereducation.com","/faq#q15","FAQ answer only","/medical-schools",2,"02 §C q15; register C","REJECTED","No defensible methodology; owner rule forbids rankings and winner badges. FAQ 15 explains why and routes to the directory.")

# E — Requirements (general)
add("E","entry requirements to study medicine in the UK (international / Nigerian)","medicine entry requirements uk for nigerian students; what do i need to study medicine in uk; requirements to study medicine in uk international students","informational","HIGH","university country pages + 2 consultancies","abdn.ac.uk/study/international/country-territory/nigeria/entry/; manchester.ac.uk/…/nigeria/entry-requirements/; gostudyin.com","/requirements","/requirements","/requirements/waec; /requirements/a-levels; /requirements/english-language; /admissions/ucat",5,"02 §A q5; 07","PUBLISHED","Hub answering the 'what do I need' question with a structured checklist and per-qualification child pages. 2026-10-03: added the 'which route is yours' table (what you hold → published route → what to check → page) and four FAQs with schema; 427 to about 950 words.")
add("E","A-levels for UK medicine from Nigeria (Cambridge International)","a level requirements medicine uk; cambridge a level nigeria medicine uk; a level schools nigeria uk medicine","informational→commercial","HIGH","Nigerian school directories, news","nigeriaprivateschools.com; nairaland.com/1837366","/requirements/a-levels","/requirements/a-levels","/medical-schools; /admissions/ucat; /study-medicine-in-the-uk/foundation-routes",4,"02 §A q9, §C q10-11; 07 A-level column","PUBLISHED","Typical A100 grade requirements and subject rules sourced per school; we name no A-level schools in Nigeria (no recommendations without evidence). Upgraded 2026-10-03 from 643 to about 1,400 words: how to read an offer, Cambridge International sittings and predicted grades, IB equivalence, the A-level years and UCAT in order, two FAQs with schema.")
add("E","English language requirements for medicine (IELTS, WAEC English)","ielts requirement medicine uk; do nigerians need ielts for uk university; waec english accepted uk university","informational","HIGH","thin; university English pages; agent help centres","assist.applyboard.com (NECO article); leadingtuition.co.uk","/requirements/english-language","/requirements/english-language","/requirements/waec; /requirements/neco; /fees/cost-of-studying-medicine-in-the-uk",4,"02 §C q5, q21; 07 English column","PUBLISHED","Per-school IELTS bands and where WAEC/NECO English counts; the two assessment layers (school and visa) explained, with the GOV.UK wording marked as not yet verified. Upgraded 2026-10-03 from 492 to about 1,250 words with two FAQs and schema.")
add("E","age / fee status / UK ENIC comparability questions","minimum age medicine uk international; uk enic nigerian degree equivalent","informational (long-tail)","MEDIUM","none specific","—","—","FAQ answers; sections on /requirements/nigerian-degree-graduate-entry","/requirements",2,"07 §planned (DATA UNAVAILABLE search budget)","RESEARCH","Research 07 could not retrieve age and fee-status rules (search budget). Collect sources first; FAQ-level answers only.")

# F — WAEC
add("F","can I study medicine in the UK with WAEC","can i study medicine in uk with waec; waec medicine uk; is waec accepted in uk universities for medicine; waec gcse equivalent uk","informational (question, high anxiety)","HIGH","two consultancy guides, forum threads, contradictory answers","theukcatpeople.co.uk (Nigeria guide); thestudentroom.co.uk t=7404771; nairaland.com/6081067","/requirements/waec","/requirements/waec","/study-medicine-in-the-uk/foundation-routes; /requirements/a-levels; /requirements/english-language; /apply-online/eligibility",5,"02 §A q6, §C q1-3, q7; 07 WAEC column","PUBLISHED","Highest-confidence Nigerian demand. Per-university published statement table with source and verified date; honest 'WAEC alone is the GCSE layer' framing.")
add("F","can I study medicine and surgery with this WAEC result (grade-specific)","can i study medicine and surgery with this result; waec grades for medicine uk; b3 c4 waec medicine uk","informational (long-tail)","HIGH","Nairaland threads only","nairaland.com/5329415; nairaland.com/3934860","/requirements/waec#what-this-means","/requirements/waec 'What this means for you' section + eligibility check","/apply-online/eligibility",4,"02 §C q7","PUBLISHED","Served in-page: grade thresholds appear only where a school publishes them (e.g. QMUL IFY 6 credits at C4; Nottingham foundation 3 Bs 2 Cs). No separate page.")

# G — NECO
add("G","NECO and UK medicine / NECO accepted in UK","neco medicine uk; which uk universities accept neco; does neco english replace ielts","informational (question)","HIGH","near-empty; one agent help-centre article","assist.applyboard.com/…/Studying-in-the-UK-with-NECO; teezab.com","/requirements/neco","/requirements/neco","/requirements/waec; /requirements/english-language",4,"02 §A q7, §C q4-5; 07 (Edinburgh, Aberdeen, QUB, Lancashire name NECO)","UPDATE","Page is thin (379 words). Upgrading on 2026-10-03 with the explicit NECO mentions table, the NECO-English acceptance list and the 'silent schools' rule; stays a separate URL because statements differ (Edinburgh names NECO; most do not).")
add("G","JAMB / UTME and UK medicine","jamb medicine uk; does jamb score count for ucas","informational (one-line answer)","MEDIUM","very weak / spam","leadingtuition.co.uk","/faq#q6","FAQ answer only","/requirements",1,"02 §A q8, §C q6; register row 33","REJECTED","Demand is domestic JAMB; the UK angle is one sentence (UCAS does not use JAMB). FAQ only, never a page.")

# H — UCAT
add("H","UCAT in Nigeria (centres, booking, dates)","ucat nigeria; ucat test centre lagos; ucat abuja; how to book ucat from nigeria; ucat 2026 dates","transactional/logistics","HIGH","one tutoring blog; no official Nigeria page","leadingtuition.co.uk/blog/ucat-nigerian-students-uk-medicine; ucat.ac.uk","/admissions/ucat","/admissions/ucat","/admissions/ucas-deadlines-2027; /medical-schools; /study-medicine-in-the-uk/from-nigeria",5,"02 §A q12-13, §C q18-20; 09 UCAT section","PUBLISHED","Strongest single content gap. Dates, structure, fee and Pearson VUE logistics are topic facts (ucat-2026) with verification status; 'if you have no UCAT today' section routes to foundation/direct schools. Upgraded 2026-10-03 from 620 to about 1,500 words: booking and access-arrangement deadlines as facts, booking from Nigeria step by step, how schools use the score (no invented cut-offs), preparation without paid courses, three FAQs with schema.")
add("H","UCAT score needed as an international / Nigerian applicant","ucat score for international students; what ucat score do i need uk medicine","informational","MEDIUM","prep companies","medify.co; themedicportal.com","/faq#q20","FAQ + per-school threshold facts on university pages","/admissions/ucat; /medical-schools",3,"02 §C q20; 07 (UCL 3060 agent-lead, QMUL 3rd decile)","PUBLISHED","Thresholds published per school only where official; FAQ 20 explains that cut-offs move yearly. No 'score predictor' page.")
add("H","UCAT preparation / courses","ucat preparation nigeria; ucat course online","commercial (tutoring)","MEDIUM","strong: Medic Mind, Medify, TheMedicPortal","medicmind.co.uk; medify.co","—","none","/admissions/ucat",1,"05 rows 7-8","REJECTED","Tutoring market is not our service and is saturated; we link to the official UCAT practice materials instead.")

# I — UCAS
add("I","admissions process hub (UCAS, UCAT, interviews, offers, visa in order)","uk medicine admissions process international; how does medical school admission work uk; medicine application timeline uk","informational","HIGH","UCAS, Medical Schools Council, prep companies","ucas.com; medschools.ac.uk","/admissions","/admissions","/admissions/ucat; /admissions/ucas-deadlines-2027; /admissions/how-to-apply",4,"09; register rows 15-17","PUBLISHED","Hub ordering the whole process for an applicant in Nigeria; children carry the specific queries. 2026-10-03: added the 'where are you today' table (position → meaning → next step) and three FAQs with schema; 470 to about 850 words.")
add("I","UCAS deadline for medicine 2027 entry / international deadline","ucas medicine deadline 2027; 15 october deadline medicine international; ucas deadline for international students medicine","informational, time-critical","HIGH","UCAS itself","ucas.com","/admissions/ucas-deadlines-2027","/admissions/ucas-deadlines-2027 (roll over each August)","/admissions/ucat; /admissions/how-to-apply; /study-medicine-in-the-uk/from-nigeria",4,"02 §A q16; 09 UCAS section","PUBLISHED","Nigeria-specific calendar (UCAT → UCAS → interview → offer → CAS → visa → TB test). Year in slug is deliberate for the cycle page; 301 on rollover per architecture 18.1. Upgraded 2026-10-03 from 526 to about 1,050 words: what each deadline means, the document timeline, the CAS-to-visa risk window, two FAQs with schema.")
add("I","how to apply to UK medicine from Nigeria (UCAS vs direct)","how to apply for medicine in uk from nigeria; ucas application nigeria step by step; direct application medical school uk","informational→action","HIGH","Nairaland step-by-step thread; agents","nairaland.com/1948639; nairaland.com/4071072","/admissions/how-to-apply","/admissions/how-to-apply","/apply-online; /admissions/ucas-deadlines-2027; /medical-schools",5,"02 §C q12-13; 09","PUBLISHED","4+1 rule, three-question statement, reference routes, document upload, Nigerian document list, direct-application schools, missed-deadline options, after-submission steps and what we do and do not do. Upgraded 2026-10-03 from 479 to about 1,350 words with three FAQs and schema.")
add("I","personal statement (3 questions) and reference for medicine","ucas personal statement medicine 2027 three questions; medicine personal statement international","informational","MEDIUM","widely served by UK prep companies","themedicportal.com; medify.co","—","/admissions/personal-statement (later, to support Tier 2)","/admissions/how-to-apply",2,"register row 27","VALIDATED","Portal checklist covers documents; a public statement page waits until the service tier needs it. Not a traffic play.")

# J — International students (places, acceptance)
add("J","international acceptance rates / places at UK medical schools","uk medical school international acceptance rate; how many international students medicine uk","informational","MEDIUM","bluepeanut, nextgenmedprep listicles","bluepeanut.com; nextgenmedprep.com","/faq#q27","FAQ + international_places facts per school","/medical-schools",3,"02 §C q26-27; 06 '# intl' column","PUBLISHED","We publish the places figure per school only where official (19 facts recorded); no computed 'acceptance rates' (no denominator data).")
add("J","scholarships for Nigerian students to study medicine in the UK","scholarships to study medicine in uk for nigerian students; scholarship study abroad with waec","informational/commercial","HIGH","unverified listicles","excelsiorscholarships.com; dofmar.com; nairaland.com/8031932","/faq#q28","FAQ answer with the honest position (very limited partial awards; Medicine usually excluded)","/fees",2,"02 §A q27, §C q28-29; 08 §5","REJECTED","Listicle intent would mislead: only tiny partial awards exist for international medicine. One FAQ, no page; re-open only if a verified, currently open scheme exists.")

# K — Fees and costs
add("K","UK medical school fees for international students","medical school fees uk international students; medicine tuition fees uk international 2027; cheapest medical school uk international","informational/commercial","HIGH","undated conflicting figures; prep companies + spam","theukcatpeople.co.uk/post/uk-medical-school-tuition-fees-for-international-students; bluepeanut.com/…/cheapest-uk-medical-schools","/fees","/fees","/fees/cost-of-studying-medicine-in-the-uk; /medical-schools/{university}; /apply-online",5,"02 §A q11-12,15, §C q22-25; 08","PUBLISHED","Dated per-school table (40 fee facts), approximate range separated from official figures. 'Cheapest' served by sorting, not by a listicle: 2026-10-03 the table gained a 'lowest published fee first' order (canonical unchanged) with a note on what cheapest does and does not mean.")
add("K","total cost of studying medicine in the UK (5–6 years, naira)","total cost of studying medicine in uk; cost of studying medicine in uk for nigerian students; how much does it cost to become a doctor in uk; cost in naira","informational","HIGH","consultancies","theukcatpeople.co.uk/post/how-much-does-it-cost-to-become-a-doctor-in-the-uk","/fees/cost-of-studying-medicine-in-the-uk","/fees/cost-of-studying-medicine-in-the-uk","/fees; /requirements/english-language; /admissions/ucat",5,"02 §C q22-25; 08 §3-4","DRAFT","Built and gated (noindex, out of sitemap) until topics student-visa, costs-2026, ucat-2026, ucas-2027 are VERIFIED in the admin queue. Naira conversion is shown as a live-rate instruction, never a fixed figure.")
add("K","living costs for medical students in the UK","living costs uk international student medicine; cost of living uk student per month","informational","MEDIUM","UKCISA, universities, generic blogs","ukcisa.org.uk; savethestudent.org","—","/fees/living-costs (later, tightly scoped)","/fees/cost-of-studying-medicine-in-the-uk",2,"register row 29; 08 §4 unsearched","RESEARCH","Research 08 §4 not yet searched; generic SERP is strong. Build only if the total-cost page's maintenance-fund facts prove insufficient and Semrush shows a Nigerian angle.")
add("K","student visa, IHS and maintenance funds for medicine","uk student visa medicine nigeria; immigration health surcharge 5 years; maintenance funds uk student visa","informational","HIGH","GOV.UK dominates","gov.uk/student-visa","/fees/cost-of-studying-medicine-in-the-uk#visa","section of the total-cost page + topic facts (student-visa)","/admissions/ucas-deadlines-2027",3,"09 visa; 08 §3","DRAFT","Lives inside the gated total-cost page; GOV.UK owns the head terms so we add only the medicine-specific layer (IHS × 5-6 years, TB test, CAS timing).")

# L — Application process (ours)
add("L","online application portal for UK medicine (Nigeria)","online application portal uk medicine; apply online uk university nigeria","transactional","MEDIUM","platforms (ApplyBoard), agents","applyboard.com; studyin-uk.com","/apply-online","/apply-online (+ /register)","/admissions/how-to-apply",3,"05 rows 3-5, 22","PUBLISHED","Our portal is the product: SMUKN-YYYY-NNNNNN applications, document checklist, approval before submission. Auth routes stay noindex.")
add("L","documents needed to apply for medicine in UK from Nigeria","documents required to study medicine in uk; waec certificate scratch card uk university; transcript uk application nigeria","informational (long-tail)","HIGH","agents","—","/admissions/how-to-apply#documents","/admissions/how-to-apply section; portal checklist","/apply-online",3,"09 documents; register row 27","PUBLISHED","Covered in-page and by the portal's document checklist; a standalone documents page only if GSC shows the query family.")

# M — Eligibility
add("M","am I eligible for UK medicine with my Nigerian qualifications (route finder)","can i get into uk medical school with waec and a levels; eligibility uk medicine nigerian degree","informational→lead","HIGH","forum only","nairaland.com","/apply-online/eligibility","/apply-online/eligibility (tool) fed by /requirements pages","/requirements/*",5,"07 rules","PUBLISHED","Instant route-category answer (standard / foundation / graduate / not yet) using published requirements; captures the lead with consent. Never says YES where a school is silent.")
add("M","switching from Arts to Medicine / non-science background","from arts to medicine uk; can i study medicine without science subjects","informational (long-tail)","MEDIUM","Nairaland thread","nairaland.com/6323922","/faq#q17","FAQ answer","/study-medicine-in-the-uk/foundation-routes; /requirements/a-levels",2,"02 §C q17","PUBLISHED","FAQ-level: the answer is 'science A-levels or a science-eligible foundation'; no page.")

# N — Interviews
add("N","medical school interviews (MMI) for international applicants / online interviews","mmi interview international students uk medicine; online interview medical school international; medicine interview nigeria","informational","MEDIUM","prep companies","themedicportal.com; medify.co","/medical-schools/{university} (interview_format facts)","/admissions/interviews (one page) once online-interview policies per school are verified","/admissions/how-to-apply",3,"register row 26; 06 interview_format (15 facts)","VALIDATED","15 interview-format facts exist; build one page when international online-interview policy is verified for ≥10 schools (QUB interviews international fee-payers online: 07). Not Nigeria-differentiated yet.")

# O — Foundation
add("O","foundation year for medicine UK international / which foundation leads to medicine","foundation year medicine uk international students; medicine foundation programme uk nigeria; which foundation leads to medicine","informational/commercial","HIGH","none; competitor snippets only","theukcatpeople.co.uk; nigeriaprivateschools.com","/study-medicine-in-the-uk/foundation-routes","/study-medicine-in-the-uk/foundation-routes","/requirements/waec; /requirements/neco; /medical-schools",5,"02 §A q26, §C q8-9; 07 foundation column; register row 18","PUBLISHED","Only routes a provider publishes as leading to Medicine (Lancashire foundation-entry MBBS, St Andrews IFM, KCL IFP, UCL UPCSE, Cardiff ISC). Everything else marked NOT PUBLISHED. Upgraded 2026-10-03 from 632 to about 1,050 words: three kinds of foundation, published statements separated from NOT PUBLISHED schools, calendar/cost/visa consequences, provider questions, two FAQs with schema.")
add("O","foundation year vs A-levels for medicine","difference between foundation year and a level uk medicine","informational (long-tail)","HIGH","Nigerian school blog","nigeriaprivateschools.com/…/168","/faq#q9","FAQ + section on foundation page","/requirements/a-levels",3,"02 §C q9","PUBLISHED","FAQ 9 plus the foundation page's comparison; no separate page.")
add("O","NCUK / pathway providers in Nigeria for UK medicine","ncuk nigeria medicine; into foundation medicine nigeria; navitas foundation medicine","commercial/navigational","MEDIUM","providers' own pages","ncuk.ac.uk; intostudy.com; navitas.com","—","provider statements as facts on the foundation page; no provider pages","/study-medicine-in-the-uk/foundation-routes",2,"07 §planned (search budget)","RESEARCH","Provider progression claims to Medicine were not retrievable in research 07; record as facts when sourced. No provider landing pages (no partnership claims).")

# P — Graduate entry
add("P","graduate entry medicine UK with a Nigerian degree","graduate entry medicine uk international students; medicine after nigerian degree uk; second degree medicine international student uk; gamsat uk international","informational","HIGH","generic PG-equivalency pages; no GEM-for-Nigerians page exists","thestudentroom.co.uk t=7524422; chester.ac.uk/international/how-to-apply/applying-for-graduate-entry-medicine/","/requirements/nigerian-degree-graduate-entry","/requirements/nigerian-degree-graduate-entry","/medical-schools?test=GAMSAT; /fees; /admissions/ucat",4,"02 §A q10, §C q31; 06 (Chester, Worcester open; Pears Cumbria home-only); 08 (Warwick, Swansea fees)","UPDATE","Unowned SERP but page is thin (317 words). Upgrading on 2026-10-03: which GEM courses accept Student-visa applicants (sourced), degree-class mapping via UK ENIC, GAMSAT vs UCAT windows, the standard-entry alternative, and the two published GEM fees.")
add("P","biomedical science / medical laboratory science UK as a route to medicine","biomedical science uk nigerian students; medical laboratory science uk for nigerians","informational (mixed with migration)","LOW","empty / jobs boards","skills-provision.com","—","section inside the graduate-entry page only","/requirements/nigerian-degree-graduate-entry",1,"02 §A q20,23; 03 verdict","REJECTED","Research 03: GEM feeder at best; HCPC/IBMS registration intent is migration, not study. One sentence on the GEM page, no page.")

# Q — GMC / registration / MDCN
add("Q","MDCN recognition of a UK medical degree (returning to Nigeria)","mdcn recognition uk medical degree; can i practise in nigeria with uk mbbs; mdcn foreign graduate assessment","informational (trust)","HIGH","empty; one competitor mention","theukcatpeople.co.uk (Nigeria guide)","/faq#q32","FAQ now; section on /working-in-the-uk when MDCN sources are verified","/working-in-the-uk",3,"02 §A q25, §C q32; 10","RESEARCH","High-value trust topic with no official source captured yet (MDCN assessment rules). Keep FAQ-level until the MDCN page is read and recorded as facts.")
add("Q","GMC registration after a UK degree (provisional registration, MLA/UKMLA)","gmc provisional registration international graduate uk; ukmla international students","informational","MEDIUM","GMC owns","gmc-uk.org","/working-in-the-uk#gmc","/working-in-the-uk section (topic facts)","/study-medicine-in-the-uk",3,"10 GMC section","DRAFT","Inside the gated working page; GMC is linked as the official source. Un-gates automatically when the topic is VERIFIED.")
add("Q","Nigerian doctor to UK (PLAB, housemanship, Nile University GMC approval)","plab for nigerian doctors; housemanship in uk nigerian graduate; nile university mbbs gmc approval","informational (different audience)","HIGH","BMA, GMC, news, forums","bma.org.uk; nairaland.com/5022863; thestudentroom.co.uk t=6990701; dailytrust.com","/faq#q34","FAQ 34 (we do not serve qualified doctors) + link-out","—",1,"02 §A q3,16, §C q34-37; register C","REJECTED","Audience is qualified doctors, outside the mission; BMA/GMC own the SERP. FAQ states the boundary and links to official sources.")

# R — Working in the UK
add("R","can I work in the UK during and after studying medicine (Graduate visa, Foundation Programme)","can i work in uk after studying medicine; graduate visa medicine uk; foundation programme international graduates uk; work 20 hours student visa","informational","HIGH","BMA owns the first page","bma.org.uk/…/studying-in-the-uk-and-your-visa","/working-in-the-uk","/working-in-the-uk","/fees/cost-of-studying-medicine-in-the-uk; /faq#q33",4,"02 §A q16, §C q33; 10; register row 25","DRAFT","Built 2026-10-03, noindex and out of the sitemap until its three topics are VERIFIED (Graduate visa 18 months from 1 Jan 2027; UKFPO prioritisation proposal in flux). Links out to GOV.UK, GMC, UKFPO, NHS England, BMA.")

# S — Long-tail questions (FAQ hub)
add("S","long-tail Nigerian questions about UK medicine (FAQ hub)","25 questions from research 02 §C: waec gcse equivalent; neco same as waec; jamb ucas; ucat slots nigeria; cost in naira; cheapest medical school; work experience nigeria; second degree medicine; recognised back in nigeria; are you an agent","informational (question)","HIGH","forum threads + competitor FAQ sections","nairaland.com; thestudentroom.co.uk; theukcatpeople.co.uk","/faq","/faq (FAQPage schema) with each answer linking into the knowledge graph; the six most Nigerian-specific also appear on the core landing page","every hub page",4,"02 §C q1-40 (29 published with sourced answers; 11 withheld)","PUBLISHED","Publish only questions with a sourced answer; 29 of the 40 are published (2026-10-03: added NECO acceptance, A-level school choice, the step-by-step process and 'is Medicine right for me', each answered from an upgraded page); 11 remain unpublished (housemanship, nursing funding, agents list, scholarships detail…) until evidence exists. Each answer links to its hub page (search-to-action chain).")
add("S","People-also-ask recovery (PAA) for the core clusters","(to be exported from Semrush Topic Research / Keyword Magic question filter)","informational","HIGH","PAA not observable via this session's search tool","—","—","answers folded into existing pages or /faq; no new URLs without evidence","—",3,"02 §E items 2, 6-7","RESEARCH","Owner action: export question-filter keywords for the 18 seeds in research 02 §E into data/semrush/lookups-YYYY-MM-DD.csv; smukn:semrush-import then updates research 02 and this register's volume/KD columns.")

# Adjacent courses (recorded under B for scope decisions)
add("B","dentistry in the UK for Nigerian students","dentistry uk nigerian students; study dentistry in uk from nigeria","informational","MEDIUM","empty Nigerian SERP","—","—","/dentistry (ONE hub page) after release 1 or if Semrush/GSC shows demand","/admissions/ucat; /fees",2,"03 verdict BUILD NOW on expertise transfer; 02 §A q15 empty SERP; register row 33a","VALIDATED","Evidence supports one page (UCAT at all schools; verified international scarcity; fees KCL/Plymouth VERIFY-ON-PAGE) but no demand data; never a section.")
add("B","pharmacy (MPharm) / nursing / public health for Nigerians","pharmacy uk nigerian students; nursing uk from nigeria; public health masters uk nigerian","informational (split study/migration/PG)","MEDIUM","moderate; universities, NHW, migration content","nairaland.com/5530820; studentship.com.ng","—","none until Semrush validation; public health = one FAQ answer only","—",1,"03; 02 §A q15,18-19; register rows 31-33b","RESEARCH","Off the medicine core; pharmacy BUILD LATER after validation; nursing split intent; public health postgraduate (FAQ only). Owner Semrush lookups 16-19 decide.")
add("B","physiotherapy / radiography UK for Nigerians","physiotherapy uk nigerian students; radiography uk nigerian students","informational","LOW","empty SERPs","—","—","none","—",1,"02 §A q15; 03 verdict DO NOT BUILD","REJECTED","Low overlap, no transferable admissions-test expertise, no data retrieved.")
add("B","study medicine abroad alternatives (North Cyprus, EU) for Nigerians","study medicine in europe nigerian students; north cyprus medicine nigerian students","commercial (agents)","HIGH","agents dominate and hijack UK intent","northcypruseducation.com; medlinkstudents.com; studymedicineeurope.com","—","none","—",1,"05 rows 9-11; register C","REJECTED","Outside the mission (UK only). We do not compete for or redirect this intent.")
add("B","generic 'study in the UK' / 'life in the UK' / per-city pages / blog / news","study in uk from nigeria; life in uk for nigerian students; study medicine in london","informational (generic)","MEDIUM","generalist agents, directories","gostudyin.com; studentship.com.ng","—","none","—",1,"register C; brief 38, 91","REJECTED","Dilutes the Nigeria→UK medicine focus; per-city pages duplicate directory data; no blog or news feed.")

# V — Healthcare course universe: one row per non-flagship subject, generated from data/healthcare/subjects.json so the
# taxonomy status and the register never disagree. Medicine's own rows are clusters B–S above.
import json as _json
_tax=_json.load(open("data/healthcare/subjects.json"))["subjects"]
_map={"RESEARCH":"RESEARCH","VALIDATED":"VALIDATED","BUILD":"BUILD","DRAFT":"DRAFT","REVIEW":"REVIEW","PUBLISHED":"PUBLISHED","INDEXING":"INDEXING","MEASURING":"MEASURING","UPDATE":"UPDATE","REJECTED":"REJECTED"}
# V00 — the one hub proposed for the non-medicine subjects (research 12 §C decision): a single allied-health overview page,
# built only when §A and §B facts are recorded as reference_facts. Until then VALIDATED, no URL, not in the sitemap.
add("V","allied health and healthcare courses in the UK for Nigerian students (overview hub)","healthcare courses in uk for nigerian students; allied health courses uk international students; nhs courses for nigerians; hcpc courses uk","informational→commercial","MEDIUM","no Nigeria-specific page observed for the family; generic agent lists","idp.com; studyin-uk.com; gostudyin.com","—","/healthcare-courses (proposed; not routed)","/study-medicine-in-the-uk; /apply-online/eligibility; every V subject row",0,"docs/research/12 §A–§C; data/healthcare/subjects.json","VALIDATED","One honest overview (which professions exist, who regulates them, which sampled universities admit international students, how registration works) serves 20 RESEARCH subjects better than 20 thin pages. Builds when the §A/§B facts are verified in reference_facts.")
for _s in _tax:
    if _s["flagship"]: continue
    _alts="; ".join(_s["alternative_names"])
    add("V",f"{_s['name']} in the UK for Nigerian students (subject cluster)",f"{_s['name'].lower()} uk for nigerian students; study {_s['name'].lower()} in uk from nigeria; {_alts}","informational→commercial",
        _s["nigerian_relevance"].split(" ")[0].strip(":;,") if _s["nigerian_relevance"]!="UNKNOWN" else "UNKNOWN",
        _s["competition"] if _s["competition"]!="NOT RESEARCHED" else "not yet observed",
        "—","—",
        "none until the subject reaches BUILD: then one hub page per subject (course → requirements → Nigerian qualifications → universities → fees → application → registration → career), never a section or a thin page",
        "/study-medicine-in-the-uk (healthcare courses hub, when built); /apply-online/eligibility",
        0,"data/healthcare/subjects.json; "+"; ".join(_s["sources"]) if _s["sources"] else "data/healthcare/subjects.json (not yet researched)",
        _map[_s["status"]],f"Taxonomy status {_s['status']}: {_s['status_reason']} Regulator: {_s['regulator']}.")

# Trust / legal (navigational, required in the register because every sitemap URL needs a row)
for path,name in [("/","Home"),("/about","About"),("/contact","Contact"),("/how-we-verify","How we verify (editorial and verification policy)"),("/privacy","Privacy notice"),("/terms","Terms of use"),("/application-terms","Application terms"),("/refund-policy","Refund policy")]:
    add("T",f"{name} (navigational / trust)",f"studymedicineuknigeria {name.lower()}","navigational","—","—","—",path,path,"—",0 if path!="/" else 5,"register row 23 (row 1 for home)","PUBLISHED","Trust or navigational page; not a keyword target. Home is the journey entry and links to every hub and to the core landing page." if path=="/" else "Trust page required by the asset register (row 23); carries no keyword target and no FAQ schema.")

with open("data/seo/decision-register.csv","w",newline="") as f:
    w=csv.DictWriter(f,fieldnames=list(rows[0].keys()),lineterminator="\n")
    w.writeheader(); w.writerows(rows)
from collections import Counter
print(len(rows),"rows"); print(Counter(r["status"] for r in rows)); print(sorted({r["current_url"] for r in rows if r["status"]=="PUBLISHED"}))
