"""Writes docs/research/14-subject-scorecard.md: one evidence scorecard per healthcare subject, built from
data/healthcare/subjects.json, data/seo/decision-register.csv and data/healthcare/courses.json. It decides nothing by
itself: it shows, per subject, the evidence the owner's promotion rule asks for (demand, Nigerian relevance, SERP
competition, commercial intent, availability, requirements, regulation, content cluster, conversion path, evidence
quality) and what is missing before the next status. Run from the repository root after build-register.py."""
import csv, json, re
tax = json.load(open("data/healthcare/subjects.json"))["subjects"]
reg = {r["id"]: r for r in csv.DictReader(open("data/seo/decision-register.csv"))}
courses = json.load(open("data/healthcare/courses.json"))["courses"]
LIVE = {"PUBLISHED", "INDEXING", "MEASURING", "UPDATE"}

def short(s, n=220):
    s = (s or "").replace("|", "/").replace("\n", " ").strip()
    return s if len(s) <= n else s[:n].rsplit(" ", 1)[0] + "…"

def evidence(s):
    blob = " ".join(str(s.get(k, "")) for k in ("international_availability", "a_level_requirements", "fees", "english_language", "register_route", "regulator"))
    facts = blob.count("FACT")
    leads = blob.count("LEAD")
    recorded = sum(len(c["facts"]) for c in courses if c["profession"] == s["slug"])
    unknown = sum(1 for k in ("international_availability", "a_level_requirements", "fees", "english_language", "nigerian_search_demand", "long_tail_demand") if str(s.get(k, "")).startswith(("NOT RESEARCHED", "NOT FOUND")))
    if facts >= 4 and recorded >= 3:
        q = "Good (official snippets for several universities, recorded for verification)"
    elif facts >= 2:
        q = "Partial (some official snippets, gaps remain)"
    elif facts or leads:
        q = "Weak (mostly aggregator leads)"
    else:
        q = "None yet"
    return q, facts, leads, recorded, unknown

def next_step(s, families):
    st = s["status"]
    if st == "REJECTED":
        return "None: rejected until new evidence (" + short(s["status_reason"], 120) + ")"
    if st in LIVE:
        return "Live: measure in Search Console once deployed"
    if st == "RESEARCH":
        return "To reach VALIDATED: Nigerian study demand (Semrush ng or clear SERP signals beyond migration content) and an international route at named universities"
    if st == "VALIDATED":
        return "To reach BUILD: regulator, per-university availability, entry and fee facts verified in reference_facts (worksheet priority 12), plus Semrush ng volumes for its families"
    return "See the decision register"

out = ["# 14. Healthcare subject scorecard", "",
       "Generated by `ops/seo/build-subject-scorecard.py` from the taxonomy, the decision register and the recorded course facts; do not edit by hand. "
       "A subject moves from data to public content only when its evidence justifies it (decision engine §7). Medicine is the flagship and the only live subject. "
       "Search volumes are not shown because Semrush has returned no API units; `data/semrush/README.md` gives the five-minute export that fills them.", "",
       "| Subject | Status | Evidence quality | Recorded course facts (unverified) | Families in register | Next step |", "|---|---|---|---|---|---|"]
order = {"PUBLISHED": 0, "VALIDATED": 1, "RESEARCH": 2, "REJECTED": 3}
rows = sorted([s for s in tax], key=lambda s: (order.get(s["status"], 9), s["name"]))
for s in rows:
    if s["flagship"]:
        out.append(f"| **{s['name']}** (flagship) | {s['status']} | Medicine dataset and topic facts (see the worksheet) | — | clusters A–S | Verify P0/P1 facts; Search Console after launch |")
        continue
    q, f, l, rec, unk = evidence(s)
    fam = [i for i in s.get("decision_register_ids", []) if i in reg]
    out.append(f"| {s['name']} | {s['status']} | {q} | {rec} | {len(fam)} ({', '.join(fam[:8])}{'…' if len(fam) > 8 else ''}) | {short(next_step(s, fam), 160)} |")
out += ["", "## Detail per subject (VALIDATED and RESEARCH)", ""]
for s in rows:
    if s["flagship"] or s["status"] == "REJECTED":
        continue
    q, f, l, rec, unk = evidence(s)
    fam = [reg[i] for i in s.get("decision_register_ids", []) if i in reg]
    conv = "Eligibility check → Apply Online (Medicine flow today; a subject-specific application path is built only at BUILD)"
    out += [f"### {s['name']} — {s['status']}", "",
            f"- **Search demand (Nigeria):** {short(s.get('nigerian_search_demand'), 300)}",
            f"- **Long-tail:** {short(s.get('long_tail_demand'), 300)}",
            f"- **Nigerian relevance:** {short(s.get('nigerian_relevance'))}",
            f"- **SERP competition:** {short(s.get('competition'))}",
            f"- **Commercial / application intent:** {short(s.get('commercial_intent'))}",
            f"- **University and course availability:** {short(s.get('international_availability'), 400)}",
            f"- **Qualification requirements:** {short(s.get('a_level_requirements'), 300)}; English: {short(s.get('english_language'), 200)}",
            f"- **Regulation:** {short(s.get('regulator'))}; route: {short(s.get('register_route'), 200)}",
            f"- **Potential content cluster:** {len(fam)} register families — " + "; ".join(f"{r['id']} {short(r['query_family'], 70)} ({r['status']})" for r in fam[:6]) + ("…" if len(fam) > 6 else ""),
            f"- **Conversion path:** {conv}",
            f"- **Evidence quality:** {q} — {f} FACT and {l} LEAD labels in the taxonomy, {rec} course facts recorded for verification, {unk} core fields still not researched",
            f"- **Next step:** {next_step(s, fam)}", ""]
open("docs/research/14-subject-scorecard.md", "w").write("\n".join(out))
print("docs/research/14-subject-scorecard.md written", len(out), "lines")
