"""Writes docs/seo/KNOWLEDGE-GRAPH.md: the topical-authority graph (Healthcare courses → subject → the nine node types)
built from data/healthcare/subjects.json and data/seo/decision-register.csv. It is a map of what exists and what the
taxonomy allows, never a build list: a node is "built" only when a live register row has that URL; everything else shows
its taxonomy status and creates no page. Run from the repository root after build-register.py."""
import csv, json
tax = json.load(open("data/healthcare/subjects.json"))["subjects"]
reg = list(csv.DictReader(open("data/seo/decision-register.csv")))
LIVE = {"PUBLISHED", "INDEXING", "MEASURING", "UPDATE"}
by_url = {}
for r in reg:
    if r["current_url"] != "—":
        by_url.setdefault(r["current_url"], r)

# The nine node types of the owner's graph, with the Medicine URL (or register id) that currently fills each one.
NODES = [
    ("Course overview", "/study-medicine-in-the-uk"),
    ("Requirements", "/requirements"),
    ("Nigerian qualifications", "/requirements/waec"),
    ("UK universities", "/medical-schools"),
    ("Fees", "/fees"),
    ("Application", "/admissions/how-to-apply"),
    ("Eligibility", "/apply-online/eligibility"),
    ("Registration", "/working-in-the-uk#gmc"),
    ("Career", "/working-in-the-uk"),
    ("Apply Online", "/apply-online"),
]
def state(url):
    r = by_url.get(url)
    if not r:
        return "not in the register"
    s = r["status"]
    if s in LIVE:
        return f"built, {s} (`{url}`, row {r['id']})"
    return f"{s} (`{url}`, row {r['id']}; noindex until its gated facts are verified)" if s == "DRAFT" else f"{s} (row {r['id']})"

out = ["# Topical-authority knowledge graph", "",
       "Generated by `ops/seo/build-knowledge-graph.py` from the healthcare taxonomy and the decision register; do not edit by hand. "
       "Root: **Healthcare courses in the UK for Nigerian students** (hub V01, VALIDATED, not yet routed). "
       "Medicine is the flagship and the only subject with built nodes. Every other subject lists its taxonomy status; "
       "a node for it is created only when the subject reaches BUILD on its own evidence and the register gives it a URL. "
       "Node names follow the owner's chain: Course → Requirements → Nigerian qualifications → UK universities → Fees → Application → Eligibility → Registration → Career → Apply Online.", "",
       "## Medicine (flagship, PUBLISHED)", "", "| Node | State |", "|---|---|"]
for name, url in NODES:
    out.append(f"| {name} | {state(url)} |")
out += ["", "Secondary Medicine nodes (spokes that deepen the chain): " + ", ".join(
    f"`{u}`" for u in sorted(by_url) if by_url[u]["status"] in LIVE and "#" not in u and "{" not in u and by_url[u]["cluster"] not in "AT"
    and u not in dict((b, a) for a, b in NODES)), ""]

out += ["## Other subjects (from the taxonomy; no node is built)", "", "| Subject | Status | Register row | Regulator | International availability (research label, not public) | What would unlock BUILD |", "|---|---|---|---|---|---|"]
for s in tax:
    if s["flagship"]:
        continue
    vid = ", ".join(i for i in s["decision_register_ids"] if i.startswith("V")) or "—"
    unlock = {"REJECTED": "nothing: rejected until new evidence",
              "VALIDATED": "regulator, availability and entry facts recorded as reference_facts with sources",
              "RESEARCH": "Nigerian demand evidence (Semrush `ng` or SERP) and the same facts as VALIDATED"}.get(s["status"], "see register")
    avail = s["international_availability"]
    avail = (avail[:140] + "…") if len(avail) > 140 else avail
    out.append(f"| {s['name']} | {s['status']} | {vid} | {s['regulator'].split(' (')[0]} | {avail.replace('|', '/')} | {unlock} |")
out += ["", "## Cross-links the graph requires (enforced by tests)", "",
        "- Home → every hub → core landing page (`/study-medicine-in-the-uk/from-nigeria`): `test_core_landing_page_is_linked_from_the_home_page_every_hub_and_the_faq`.",
        "- Every live informational page → Eligibility or Apply Online: `test_every_live_informational_page_links_to_the_eligibility_check_or_apply_online`.",
        "- Every indexable URL ↔ one live register row: `SeoDecisionRegisterTest`.",
        "- Subject status ↔ register cluster V: `HealthcareTaxonomyTest`.", ""]
open("docs/seo/KNOWLEDGE-GRAPH.md", "w").write("\n".join(out))
print("docs/seo/KNOWLEDGE-GRAPH.md written", len(out), "lines")
