#!/usr/bin/env python3
"""Writes docs/seo/UNIVERSITY-ASSESSMENT.md: every university record, its five core publication facts, the publication
decision with its reason, and the official pages that need human verification (bot challenge or unreadable).
Usage: python3 ops/seo/build-university-assessment.py <database.sqlite> [blocked.json]
The database must have the committed decisions applied (as on deploy: migrate, smukn:reference-sync, smukn:facts-import)."""
import csv, json, sqlite3, sys

db = sqlite3.connect(sys.argv[1])
blocked = json.load(open(sys.argv[2])) if len(sys.argv) > 2 else {}
published = {e['slug']: e['register'] for e in json.load(open('data/medical-schools/publication.json'))['published']}
register = {r['id']: r for r in csv.DictReader(open('data/seo/decision-register.csv'))}
evidence = {'brighton-sussex': '02 §A q4', 'buckingham': '02 §A q9', 'aberdeen': '02 §A q5', 'cardiff': '02 §A q5', 'manchester': '02 §A q5', 'edinburgh': '02 §A q5'}
CORE = [('International applicants', 'University', ['international_accepted', 'international_places_open']),
        ('Nigeria / WAEC statement', 'University', ['waec_neco_statement']),
        ('English requirement', 'University', ['english_requirement', 'english_language_requirement']),
        ('International fee with year', 'Course', ['international_fee_gbp']),
        ('Application route', 'Course', ['application_route'])]


def state(stype, sid, keys):
    rows = db.execute(f"select verification_status, academic_year from reference_facts where subject_type like ? and subject_id = ? and key in ({','.join('?' * len(keys))})", ('%' + stype, sid, *keys)).fetchall()
    if any(s == 'VERIFIED' for s, _ in rows):
        years = sorted({y for s, y in rows if s == 'VERIFIED' and y})
        return 'verified' + (f" ({years[-1]})" if stype == 'Course' and years else '')
    return 'not verified' if rows else 'no record'


lines, counts = [], {}
for uid, slug, name, policy in db.execute('select id, slug, name, international_policy from universities order by name').fetchall():
    courses = db.execute('select id, title from courses where university_id = ? order by entry_type = "standard" desc, id', (uid,)).fetchall()
    medicine = [c for c in courses if any(w in c[1].upper() for w in ('MEDICINE', 'MBBS', 'MBCHB', 'BMBS', 'MBBCH', 'MB BS', 'MB CHB', 'BM BS', 'MB BCH', 'MB, BCHIR', 'BM BCH'))] or ([] if courses else [(None, '')])
    cid = medicine[0][0] if medicine else None
    core = [state(t, uid if t == 'University' else cid, k) if (t == 'University' or cid) else 'no record' for _, t, k in CORE]
    done = all(c.startswith('verified') for c in core)
    if courses and not medicine:
        decision, reason = 'Not a medical school', 'Recorded only for another subject (' + ', '.join(c[1] for c in courses) + '); no UK primary medical degree; never listed as a medical school.'
    elif slug in published:
        r = register.get(published[slug], {})
        decision, reason = 'PUBLISHED (indexable, in sitemap)', f"Register {published[slug]}: threshold met with Nigerian SERP evidence ({evidence.get(slug, 'see register')})."
    elif policy == 'home_only':
        decision, reason = 'Noindex: home students only', 'The university publishes that it does not admit international (overseas fee) applicants to this course; listed in the directory so a Nigerian applicant does not waste a choice.'
    elif done:
        decision, reason = 'Noindex: verified, no Nigerian demand evidence', 'All five core facts verified; no Nigerian SERP, Search Console or Semrush evidence recorded for this school yet (DECISION-ENGINE §8.3). Publish when Search Console shows impressions for its name or a Nigeria-specific SERP names it.'
    else:
        missing = [CORE[i][0] for i, c in enumerate(core) if not c.startswith('verified')]
        decision, reason = 'Noindex: core facts incomplete', 'Missing: ' + ', '.join(missing) + '.'
    if blocked.get(slug):
        reason += ' Human verification needed (pages blocked to automated reading): ' + '; '.join(blocked[slug][:4]) + '.'
    counts[decision] = counts.get(decision, 0) + 1
    lines.append(f"| {name} | {policy} | " + ' | '.join(core) + f" | **{decision}** | {reason} |")

out = ['# University assessment (generated)', '',
       'Generated by `ops/seo/build-university-assessment.py` from a database with every committed decision applied. Every value',
       'marked *verified* was read on the official page with the quotation recorded in `data/verification/decisions-*.csv`',
       '(DECISION-ENGINE §8). Do not edit by hand.', '', '## Summary', '']
out += [f'- {k}: {v}' for k, v in sorted(counts.items())]
out += ['', '## Every record', '', '| University | Policy | International | Nigeria / WAEC | English | Fee (year) | Route | Decision | Reason / next action |', '|---|---|---|---|---|---|---|---|---|'] + lines

# Extended record: the remaining fields of the owner's 55-school checklist, each with its evidence status.
# V = verified on the official page; NP = the university does not publish it (recorded NOT_PUBLISHED); p = recorded, not
# yet verified (hidden in production); - = not recorded. "Last verified" is the newest verification date of the record.
EXT = [('Degree / UCAS code', 'Course', ['ucas_code']), ('Duration', 'Course', ['course_length_years']), ('Admissions test', 'Course', ['admissions_test']),
       ('Interview', 'Course', ['interview_format']), ('A-level / IB', 'University', ['a_level_requirement']), ('Foundation route', 'University', ['foundation_route']),
       ('Graduate entry', 'University', ['gem_international']), ('International places', 'University', ['international_places', 'international_places_open'])]


def mark(stype, sid, keys):
    if sid is None:
        return '-'
    rows = [r[0] for r in db.execute(f"select verification_status from reference_facts where subject_type like ? and subject_id = ? and key in ({','.join('?' * len(keys))})", ('%' + stype, sid, *keys)).fetchall()]
    return 'V' if 'VERIFIED' in rows else ('NP' if 'NOT_PUBLISHED' in rows else ('p' if rows else '-'))


ext = []
for uid, slug, name, city in db.execute('select id, slug, name, city from universities order by name').fetchall():
    courses = db.execute("select id, title, award, entry_type from courses where university_id = ? order by entry_type = 'standard' desc, id", (uid,)).fetchall()
    med = [c for c in courses if any(w in (c[1] or '').upper() for w in ('MEDICINE', 'MBBS', 'MBCHB', 'BMBS', 'MBBCH', 'MB BS', 'MB CHB', 'BM BS', 'MB BCH', 'MB, BCHIR', 'BM BCH'))]
    if courses and not med:
        continue
    c = med[0] if med else (None, '', None, None)
    last = db.execute("select max(substr(verified_at,1,10)) from reference_facts where verification_status='VERIFIED' and ((subject_type like '%University' and subject_id=?) or (subject_type like '%Course' and subject_id=?))", (uid, c[0] or -1)).fetchone()[0] or '—'
    srcs = db.execute("select count(distinct source_url) from reference_facts where verification_status='VERIFIED' and ((subject_type like '%University' and subject_id=?) or (subject_type like '%Course' and subject_id=?))", (uid, c[0] or -1)).fetchone()[0]
    marks = [mark(t, uid if t == 'University' else c[0], k) for _, t, k in EXT]
    demand = evidence.get(slug, 'none recorded')
    ext.append(f"| {name} | {city or '—'} | {(c[2] or '—')} · {c[3] or '—'} | " + ' | '.join(marks) + f" | {srcs} | {last} | {demand} |")
out += ['', '## Extended record (every field of the 55-school checklist)', '',
        '`V` verified on the official page · `NP` not published by the university · `p` recorded, awaiting verification (hidden in production) · `-` not recorded.',
        'The UCAS Medicine deadline (15 October 2026, 18:00 UK time) applies to every school whose route includes UCAS; it is a verified UCAS fact, shown on each school page.',
        '', '| University | City | Award · entry | ' + ' | '.join(e[0] for e in EXT) + ' | Official sources | Last verified | Nigerian demand evidence |',
        '|' + '---|' * (len(EXT) + 6)] + ext
open('docs/seo/UNIVERSITY-ASSESSMENT.md', 'w').write('\n'.join(out) + '\n')
print(counts)
