#!/usr/bin/env python3
"""Writes docs/seo/UNIVERSITY-ASSESSMENT.md: every university record, its five core publication facts, the publication
decision with its reason, and the official pages that need human verification (bot challenge or unreadable).
Usage: python3 ops/seo/build-university-assessment.py <database.sqlite> [blocked.json]
The database must have the committed decisions applied (as on deploy: migrate, smukn:reference-sync, smukn:facts-import)."""
import csv, json, sqlite3, sys

db = sqlite3.connect(sys.argv[1])
blocked = json.load(open(sys.argv[2])) if len(sys.argv) > 2 else {}
published = {e['slug']: e['register'] for e in json.load(open('data/medical-schools/publication.json'))['published']}
register = {r['id']: r for r in csv.DictReader(open('data/seo/decision-register.csv'))}
evidence = {'brighton-sussex': '02 §A q4', 'buckingham': '02 §A q9', 'aberdeen': '02 §A q5', 'cardiff': '02 §A q5', 'manchester': '02 §A q5', 'edinburgh': '02 §A q5', 'cambridge': 'autocomplete gl=ng 2026-10-06', 'glasgow': 'autocomplete gl=ng 2026-10-06', 'nottingham': 'autocomplete gl=ng 2026-10-06'}
CORE = [('International applicants', 'University', ['international_accepted', 'international_places_open']),
        ('Nigeria / WAEC statement', 'University', ['waec_neco_statement']),
        ('English requirement', 'University', ['english_requirement', 'english_language_requirement']),
        ('International fee with year', 'Course', ['international_fee_gbp']),
        ('Application route', 'Course', ['application_route'])]


def state(stype, sid, keys):
    rows = db.execute(f"select verification_status, academic_year from reference_facts where subject_type like ? and subject_id = ? and key in ({','.join('?' * len(keys))})", ('%' + stype, sid, *keys)).fetchall()
    if any(s == 'VERIFIED' for s, _ in rows):
        years = sorted({y for s, y in rows if s == 'VERIFIED' and y})
        return 'verified' + (f" ({years[-1]})" if stype == 'Course' and years else '')
    return 'not verified' if rows else 'no record'


lines, counts = [], {}
for uid, slug, name, policy in db.execute('select id, slug, name, international_policy from universities order by name').fetchall():
    courses = db.execute('select id, title from courses where university_id = ? order by entry_type = "standard" desc, id', (uid,)).fetchall()
    medicine = [c for c in courses if any(w in c[1].upper() for w in ('MEDICINE', 'MBBS', 'MBCHB', 'BMBS', 'MBBCH', 'MB BS', 'MB CHB', 'BM BS', 'MB BCH', 'MB, BCHIR', 'BM BCH'))] or ([] if courses else [(None, '')])
    cid = medicine[0][0] if medicine else None
    core = [state(t, uid if t == 'University' else cid, k) if (t == 'University' or cid) else 'no record' for _, t, k in CORE]
    done = all(c.startswith('verified') for c in core)
    if courses and not medicine:
        decision, reason = 'Not a medical school', 'Recorded only for another subject (' + ', '.join(c[1] for c in courses) + '); no UK primary medical degree; never listed as a medical school.'
    elif slug in published:
        r = register.get(published[slug], {})
        decision, reason = 'PUBLISHED (indexable, in sitemap)', f"Register {published[slug]}: threshold met with Nigerian SERP evidence ({evidence.get(slug, 'see register')})."
    elif policy == 'home_only':
        decision, reason = 'Noindex: home students only', 'The university publishes that it does not admit international (overseas fee) applicants to this course; listed in the directory so a Nigerian applicant does not waste a choice.'
    elif done:
        decision, reason = 'Noindex: verified, no Nigerian demand evidence', 'All five core facts verified; no Nigerian SERP, Search Console or Semrush evidence recorded for this school yet (DECISION-ENGINE §8.3). Publish when Search Console shows impressions for its name or a Nigeria-specific SERP names it.'
    else:
        missing = [CORE[i][0] for i, c in enumerate(core) if not c.startswith('verified')]
        decision, reason = 'Noindex: core facts incomplete', 'Missing: ' + ', '.join(missing) + '.'
    if blocked.get(slug):
        reason += ' Human verification needed (pages blocked to automated reading): ' + '; '.join(blocked[slug][:4]) + '.'
    counts[decision] = counts.get(decision, 0) + 1
    lines.append(f"| {name} | {policy} | " + ' | '.join(core) + f" | **{decision}** | {reason} |")

out = ['# University assessment (generated)', '',
       'Generated by `ops/seo/build-university-assessment.py` from a database with every committed decision applied. Every value',
       'marked *verified* was read on the official page with the quotation recorded in `data/verification/decisions-*.csv`',
       '(DECISION-ENGINE §8). Do not edit by hand.', '', '## Summary', '']
out += [f'- {k}: {v}' for k, v in sorted(counts.items())]
out += ['', '## Every record', '', '| University | Policy | International | Nigeria / WAEC | English | Fee (year) | Route | Decision | Reason / next action |', '|---|---|---|---|---|---|---|---|---|'] + lines
open('docs/seo/UNIVERSITY-ASSESSMENT.md', 'w').write('\n'.join(out) + '\n')
print(counts)
