"""Audit every indexable page against the decision register (docs/seo/PAGE-AUDIT.md, generated; never edit by hand).

For each sitemap URL: the register rows it serves (target query, intent, Nigerian relevance, status), title and H1,
words in <main>, in-body inbound links from other sitemap pages, and whether the page body itself routes the reader
to the eligibility check and to Apply Online (header, footer and the floating button are excluded: a reader who
finishes the content should meet the next step in it). Flags: no register row, duplicate title or H1, title and H1
leading with another page's phrase, thin body, few inbound links, no in-body route to eligibility or to apply.

Usage: python3 ops/seo/page-audit.py [BASE_URL]   (a running local site, e.g. php artisan serve)
"""
import collections, csv, html as htmllib, re, sys, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = (sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:8000").rstrip("/")
ELIG, APPLY = "/apply-online/eligibility", "/apply-online"


def get(path):
    return urllib.request.urlopen(BASE + path).read().decode()


def text(fragment):
    fragment = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", fragment, flags=re.S)
    return htmllib.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", fragment))).strip()


def norm(path):
    path = path.split("#")[0].split("?")[0].rstrip("/")
    return path or "/"


register = list(csv.DictReader(open(ROOT / "data/seo/decision-register.csv", encoding="utf-8")))
by_url = collections.defaultdict(list)
for row in register:
    for col in ("current_url", "recommended_page"):
        u = (row.get(col) or "").strip()
        if u.startswith("/"):
            by_url[norm(u)].append(row)
            break

paths = [norm(u.replace(BASE, "") or "/") for u in re.findall(r"<loc>([^<]+)", get("/sitemap.xml"))]
pages, inbound = {}, collections.Counter()
for p in paths:
    page = get(p)
    main = page.split("<main", 1)[1].split("</main>", 1)[0] if "<main" in page else page
    links = {norm(l) for l in re.findall(r'href="(?:https?://[^/"]+)?(/[^"]*)"', main)}
    links = {l for l in links if not l.startswith(("/images", "/fonts", "/build"))}
    title = text(re.search(r"<title>(.*?)</title>", page, re.S).group(1)) if "<title>" in page else ""
    h1m = re.search(r"<h1[^>]*>(.*?)</h1>", page, re.S)
    pages[p] = {
        "title": title, "h1": text(h1m.group(1)) if h1m else "", "words": len(text(main).split()),
        "elig": ELIG in links or p == ELIG, "apply": any(l == APPLY or l.startswith(APPLY + "/") and l != ELIG for l in links) or p == APPLY,
        "links": links - {p},
    }
    for l in links - {p}:
        inbound[l] += 1

titles = collections.Counter(v["title"] for v in pages.values())
h1s = collections.Counter(v["h1"].lower() for v in pages.values())
lead = lambda s: " ".join(re.sub(r"[^a-z0-9 ]", " ", s.split(":")[0].lower()).split())
leads = collections.Counter(lead(v["title"].split(" | ")[0]) for v in pages.values())

# Legal pages state terms; they carry no sales routes by design and their length follows the terms, not search intent.
LEGAL = {"/privacy", "/terms", "/application-terms", "/refund-policy"}
rows, flagged = [], 0
for p in paths:
    v, regs = pages[p], by_url.get(p, [])
    flags = []
    if not regs and p != "/":
        flags.append("no register row")
    if titles[v["title"]] > 1:
        flags.append("duplicate title")
    if v["h1"] and h1s[v["h1"].lower()] > 1:
        flags.append("duplicate H1")
    if leads[lead(v["title"].split(" | ")[0])] > 1:
        flags.append("title lead shared")
    if p in LEGAL:
        flags = [f for f in flags if f.startswith(("duplicate", "title lead", "no register"))] + ["legal: no sales routes by design"]
    elif v["words"] < 300:
        flags.append(f"thin ({v['words']} words)")
    if p not in LEGAL:
        if inbound[p] < 3 and p != "/":
            flags.append(f"{inbound[p]} inbound")
        if not v["elig"]:
            flags.append("no route to eligibility")
        if not v["apply"]:
            flags.append("no route to apply")
    flagged += any(not f.startswith("legal") for f in flags)
    reg = "; ".join(f"{r['id']} {r['status']}" for r in regs) or "–"
    query = regs[0]["query_family"] if regs else "–"
    intent = regs[0]["intent"] if regs else "–"
    rel = regs[0]["nigerian_relevance"] if regs else "–"
    rows.append(f"| `{p}` | {reg} | {query} | {intent} | {rel} | {v['h1'] or '–'} | {v['words']} | {inbound[p]} | {'yes' if v['elig'] else '**no**'} | {'yes' if v['apply'] else '**no**'} | {', '.join(flags) or 'ok'} |")

out = ["# Indexable page audit (generated)", "",
       f"Generated by `python3 ops/seo/page-audit.py` against a local build: {len(paths)} sitemap URLs, {flagged} with at least one flag. "
       "Inbound = links inside `<main>` of other sitemap pages; routes count only links inside `<main>` (the header, footer and floating "
       "Apply button are on every page and are not counted). Register rows from `data/seo/decision-register.csv` (`current_url`, else "
       "`recommended_page`). Search volume and difficulty are not shown here: they exist only once a dated Semrush export is recorded "
       "(`data/semrush/README.md`).", "",
       "| URL | Register | Target query family | Intent | Nigerian relevance | H1 | Words | Inbound | Eligibility | Apply | Flags |",
       "|---|---|---|---|---|---|---|---|---|---|---|", *rows, ""]
(ROOT / "docs/seo/PAGE-AUDIT.md").write_text("\n".join(out), encoding="utf-8")
print(f"{len(paths)} pages, {flagged} flagged -> docs/seo/PAGE-AUDIT.md")
