<x-layouts.public :seo="$seo">
<article class="container-site pt-6 pb-10">
    @include('content._page-head', ['eyebrow' => 'About', 'title' => 'About Study Medicine UK Nigeria', 'lede' => 'An independent, evidence-led application-support service for Nigerian students applying to study Medicine and directly related healthcare courses in the United Kingdom.', 'seo' => $seo])
    <div class="mt-10 grid lg:grid-cols-12 gap-10">
        <div class="lg:col-span-8 prose-site">
            <h2>Why this exists</h2>
            <p>Nigerian students asking "can my WAEC get me into UK medicine?", "what does it cost?" or "where do I sit the UCAT?" find contradictory answers from agents, listicles and forums. UK medical schools publish most of what matters, but across dozens of pages in dozens of formats. We read those pages, record what each school says with its source and the date we checked it, and build a platform around that evidence: a directory, requirement and fee guides, and an application portal where nothing is submitted without your approval.</p>
            <h2>How we work</h2>
            <ul><li><strong>Evidence first.</strong> Every requirement, fee and date on this site is a separate record with an official source and a verification status. If we have not confirmed it on the official page, you do not see it.</li><li><strong>No fabrication.</strong> No rankings, testimonials, success rates, partnership claims or student numbers we cannot evidence.</li><li><strong>Your application stays yours.</strong> We prepare and check; where the university requires you to submit personally, you do. Submission by us happens only under a signed agreement, and we hold none today.</li><li><strong>Your data is protected.</strong> Documents are stored privately and encrypted where most sensitive; access is logged; you can export or delete your data.</li></ul>
            <h2>What we never claim</h2>
            <p>We do not guarantee offers, interviews, visas or scholarships. We are not an agent of, or affiliated with, any university, UCAS, the British Council or the GMC. We receive no commission from universities. Universities named on this site are referenced for information only; admissions decisions are made solely by them. See <a href="{{ route('status') }}">Our status</a>.</p>
            <h2>How we are paid</h2>
            <p>Students pay us directly for a defined service level, listed with what is included and excluded on the <a href="{{ route('apply.services') }}">services page</a>, and nothing is charged until our team has reviewed your profile, you have seen the fee for each service open to you, chosen one and paid. Our fee is separate from university tuition, application and test fees, English tests, visa and health-surcharge costs, which you pay to those organisations yourself. We receive no commission from any university, which is why we can say plainly when a school is not open to you. Refunds follow the published <a href="{{ route('legal.refunds') }}">refund policy</a>.</p>
            <h2>What you can check for yourself</h2>
            <ul><li>Every fact carries its official source link and a verification label; the <a href="{{ route('verify') }}">How we verify</a> page explains each label and shows live counts of what is verified and what is pending.</li><li>Our legal status, agreements (none) and training certificates are dated on <a href="{{ route('status') }}">Our status</a>, with the sector vocabulary so you can test any service's claims, including ours.</li><li>Any university we describe publishes its own list of appointed representatives; we do not appear on them, and we say so.</li></ul>
            <h2>Who we are</h2>
            <p>Study Medicine UK Nigeria is operated by {{ config('site.legal_name') ?? 'an independent team' }}. Company details and registrations are listed, with dates, on <a href="{{ route('status') }}">Our status</a>. Our editorial rules are on <a href="{{ route('verify') }}">How we verify</a>; if you find an error, the <a href="{{ route('contact') }}">contact page</a> says what to send. If you are starting from scratch, begin with the <a href="{{ route('medicine.nigeria') }}">guide for applicants from Nigeria</a>. Contact us at <a href="mailto:{{ config('site.email') }}">{{ config('site.email') }}</a>.</p>
        </div>
        <aside class="lg:col-span-4"><div class="card"><p class="eyebrow mb-3">Our status</p><p class="text-[0.9375rem] text-ink-700">{{ config('site.status_statement') }}</p><a href="{{ route('status') }}" class="btn btn-tertiary mt-3">Read the full statement</a></div></aside>
    </div>
    <x-cta-band class="mt-12" title="See where you stand" :href="route('apply.eligibility')" label="Check your eligibility" :secondary-href="route('apply.index')" secondary-label="Apply Online">The eligibility check compares your qualifications with what UK medical schools publish: seven questions, no account needed.</x-cta-band>
</article>
</x-layouts.public>
