<x-layouts.public :seo="$seo">
<article class="container-site pt-6 pb-10"><div class="max-w-3xl prose-site">
    @include('content._page-head', ['eyebrow' => 'Legal', 'title' => 'Privacy notice', 'lede' => 'How Study Medicine UK Nigeria collects, uses, stores and shares your personal data under the UK GDPR and the Nigeria Data Protection Act 2023.', 'seo' => $seo])
    <p class="text-[0.8125rem] text-ink-500 mt-4">Version 0.9.3, 6 October 2026 — published for transparency and under legal review; the reviewed version will replace it here.</p>
    <p>This notice sits alongside the <a href="{{ route('legal.terms') }}">website terms of use</a>; for the paid service, the <a href="{{ route('legal.application-terms') }}">application service terms</a> also apply.</p>
    <h2>Who we are</h2><p>{{ config('site.legal_name') ?? 'Study Medicine UK Nigeria' }} ("we") is the data controller for this website and the student portal.{{ config('site.address') ? ' Address: '.config('site.address').'.' : '' }}{{ config('site.ico_number') ? ' ICO registration: '.config('site.ico_number').'.' : '' }} Contact: <a href="mailto:{{ config('site.email') }}">{{ config('site.email') }}</a>.</p>
    <h2>What we collect</h2><ul><li>Account and contact details: name, email, phone, WhatsApp, state and country.</li><li>Application data you enter: education history, grades, test results, experience, personal statement, referee details, declarations.</li><li>Documents you upload: passport, certificates, transcripts, test reports, statements, references.</li><li>Payment records: amount, status and Stripe references. We never receive your card number.</li><li>Eligibility-check answers and messages you send us.</li><li>Technical data: IP address, device and browser information, and access logs for documents.</li></ul>
    <h2>Why we use it and on what basis</h2><ul><li>To provide the service you asked for (contract): assessing your profile, building your checklist, reviewing documents, preparing and tracking your application.</li><li>To keep records of your approvals and our actions (legitimate interests and legal obligation).</li><li>To contact you about your application and, only with consent, about related information.</li><li>To protect the service (legitimate interests): security logging, fraud and abuse prevention.</li></ul>
    <h2>Who we share it with</h2><p>Only with the university or official body you approve a submission to, with the service providers below, and where the law requires.</p>
    <ul>
        <li><strong>Hostinger</strong> (processor): hosts the website, the portal, its database and your documents, and delivers our email.</li>
        <li><strong>Stripe</strong>: takes card payments on its own payment page. We receive the amount, status and Stripe references, never your card number. Stripe is also a controller in its own right for fraud prevention and its legal duties.</li>
        <li><strong>GitHub</strong> (processor): stores our encrypted database backups. The backups are encrypted before they leave our server and GitHub does not hold the key.</li>
        <li><strong>Google</strong>: Google Analytics runs on the public site only if you accept analytics cookies, and no Google script ever loads in the portal. If you accepted, our server also tells Google Analytics when you complete a portal step yourself (for example "application started" or "payment started"), using only the anonymous browser identifier Google set on the public site, your service tier and intake year; never names, email addresses, application numbers, documents or what you wrote. Google keeps analytics data for 14 months.</li>
        <li><strong>WhatsApp (Meta)</strong>: only if you choose to message us there; WhatsApp is a controller for its own service.</li>
    </ul>
    <p> We never sell data and we share nothing with universities before your recorded approval.</p>
    <h2>International transfers</h2><p>{{ config('site.hosting_region') ? 'Our hosting is located in '.config('site.hosting_region').'.' : "Our hosting provider's data-centre location is stated in our records and available on request." }} Transfers to Nigeria (to you) and from Nigeria (from you) are necessary for the contract. Some providers (Stripe, GitHub, Google) may process data in the United States; those transfers rely on the UK's adequacy regulations or the providers' standard contractual safeguards.</p>
    <h2>How long we keep it</h2><ul>
        <li>An application that is not yet submitted and has had no activity for 24 months is closed.</li>
        <li>Documents are deleted 12 months after an application closes (withdrawn, closed or completed).</li>
        <li>24 months after an application closes, everything you or we wrote is removed: form answers, messages, notes, document titles and file names, submission notes and references, and the copy of the package you approved. What stays are dates, stages, amounts and a fingerprint of the approved package.</li>
        <li>Payment and approval records are deleted 6 years after the application closed (accounting and evidence). Stripe event records keep only payment references, amounts and statuses, never your name, email or address.</li>
        <li>Eligibility-check records and our first-party usage counts are deleted after 24 months; an account with nothing left to keep is anonymised 24 months after its last activity. Access and security logs are kept 24 months.</li>
        <li>Our encrypted backups expire within 30 days. Our host also keeps its own server backups under its standard schedule.</li>
    </ul><p>These rules are applied automatically every week.</p>
    <h2>Security</h2><p>Documents are stored privately, never at public URLs, and checked on upload: the file type is read from the content, PDFs with scripts and Word files with macros are refused, and images are re-encoded to remove hidden data. Documents are encrypted at rest. Every document access is logged; failed sign-ins and two-step verification failures are logged for security; staff access is role-based and requires two-step verification.</p>
    <h2>Decisions about you</h2><p>The eligibility check and route map are guidance generated from published requirements. We make no decision with legal or similarly significant effect by automated means; admission decisions are made by universities.</p>
    <h2>Your rights</h2><p>You can access, correct, export and delete your data, object to or restrict processing, and withdraw consent. Download your data from the Profile page in your portal; to delete your account, choose <em>Request deletion</em> there or email us, and we complete it within 30 days unless a submission in progress requires us to keep records (we will tell you if so). You may complain to the UK Information Commissioner's Office or the Nigeria Data Protection Commission.</p>
    <h2>Cookies</h2><p>We use strictly necessary cookies for sign-in and security. Google Analytics cookies are set on the public site only if you choose <em>Accept analytics</em> in the banner; you can change your mind at any time with <em>Cookie settings</em> at the foot of every page, which also removes the Google Analytics cookies. The student portal never loads third-party analytics. Separately, we keep first-party counts of application steps (for example “application started”, “document uploaded”) that contain no names, email addresses or application numbers (a keyed code links the steps of one application), to improve the service; they are deleted after 24 months.</p>
</div></article>
</x-layouts.public>
