<x-layouts.public :seo="$seo">
<article class="container-site pt-6 pb-10"><div class="max-w-3xl prose-site">
    @include('content._page-head', ['eyebrow' => 'Legal', 'title' => 'Privacy notice', 'lede' => 'How Study Medicine UK Nigeria collects, uses, stores and shares your personal data under the UK GDPR and the Nigeria Data Protection Act 2023.', 'seo' => $seo])
    <p class="text-[0.8125rem] text-ink-500 mt-4">Version 0.9, 3 October 2026 — published for transparency and under legal review; the reviewed version will replace it here.</p>
    <h2>Who we are</h2><p>{{ config('site.legal_name') ?? 'Study Medicine UK Nigeria' }} ("we") is the data controller for this website and the student portal. Contact: <a href="mailto:{{ config('site.email') }}">{{ config('site.email') }}</a>.</p>
    <h2>What we collect</h2><ul><li>Account and contact details: name, email, phone, WhatsApp, state and country.</li><li>Application data you enter: education history, grades, test results, experience, personal statement, referee details, declarations.</li><li>Documents you upload: passport, certificates, transcripts, test reports, statements, references.</li><li>Payment records: amount, status and Stripe references. We never receive your card number.</li><li>Eligibility-check answers and messages you send us.</li><li>Technical data: IP address, device and browser information, and access logs for documents.</li></ul>
    <h2>Why we use it and on what basis</h2><ul><li>To provide the service you asked for (contract): assessing your profile, building your checklist, reviewing documents, preparing and tracking your application.</li><li>To keep records of your approvals and our actions (legitimate interests and legal obligation).</li><li>To contact you about your application and, only with consent, about related information.</li><li>To protect the service (legitimate interests): security logging, fraud and abuse prevention.</li></ul>
    <h2>Who we share it with</h2><p>Only with the university or official body you approve a submission to, with our processors (hosting, email delivery, Stripe for payments) under contract, and where the law requires. We never sell data and we share nothing with universities before your recorded approval.</p>
    <h2>International transfers</h2><p>Data is hosted in the UK/EU. Transfers to Nigeria (to you) and from Nigeria (from you) are necessary for the contract. Processors outside the UK are covered by appropriate safeguards.</p>
    <h2>How long we keep it</h2><p>Active applications for the cycle. Documents are deleted 12 months after an application closes; application records are anonymised after 24 months, except payment records (6 years) and approval records (6 years) which keep dates and fingerprints but not documents. Access logs are kept 24 months. Backups expire on a 30-day cycle.</p>
    <h2>Security</h2><p>Documents are stored privately, never at public URLs, scanned on upload, encrypted where most sensitive, and every access is logged. Staff access is role-based.</p>
    <h2>Your rights</h2><p>You can access, correct, export and delete your data, object to or restrict processing, and withdraw consent. Use the Profile page in your portal or email us. You may complain to the UK Information Commissioner's Office or the Nigeria Data Protection Commission.</p>
    <h2>Cookies</h2><p>We use strictly necessary cookies for sign-in and security. Google Analytics cookies are set on the public site only if you choose <em>Accept analytics</em> in the banner; you can change your mind by clearing cookies for this site. The student portal never loads third-party analytics. Separately, we keep first-party counts of application steps (for example “application started”, “document uploaded”) that contain no names, email addresses or application numbers, to improve the service.</p>
</div></article>
</x-layouts.public>
