<?php

namespace App\Support;

/**
 * Per-page SEO data. Built by controllers, rendered by partials/seo.blade.php.
 * Keeps metadata, canonical, robots, Open Graph, breadcrumbs and JSON-LD in one object
 * so every template emits the same, complete head.
 */
class Seo
{
    public string $title;

    public string $description;

    public ?string $canonical = null;

    public bool $noindex = false;

    public string $ogType = 'website';

    public ?string $ogImage = null;

    /** @var array<int, array{label:string, url?:string}> */
    public array $breadcrumbs = [];

    /** @var array<int, array<string, mixed>> */
    public array $jsonLd = [];

    public ?string $lastReviewed = null;

    public ?string $intakeYear = null;

    public function __construct(string $title, ?string $description = null)
    {
        $this->title = $title;
        $this->description = $description ?? config('site.default_description');
    }

    public static function make(string $title, ?string $description = null): static
    {
        return new static($title, $description);
    }

    public function canonical(?string $url): static
    {
        $this->canonical = $url;

        return $this;
    }

    public function noindex(bool $v = true): static
    {
        $this->noindex = $v;

        return $this;
    }

    public function article(): static
    {
        $this->ogType = 'article';

        return $this;
    }

    public function image(?string $path): static
    {
        $this->ogImage = $path;

        return $this;
    }

    public function reviewed(?string $date, ?string $intakeYear = null): static
    {
        $this->lastReviewed = $date;
        $this->intakeYear = $intakeYear;

        return $this;
    }

    /** @param array<int, array{label:string, url?:string}> $crumbs */
    public function breadcrumbs(array $crumbs): static
    {
        $this->breadcrumbs = $crumbs;

        return $this;
    }

    /** @param array<string, mixed> $schema */
    public function jsonLd(array $schema): static
    {
        $this->jsonLd[] = $schema;

        return $this;
    }

    public function fullTitle(): string
    {
        $site = config('site.name');
        $full = "{$this->title} | {$site}";

        // Search snippets truncate around 60–65 characters: keep the brand suffix only while it fits.
        return (str_contains($this->title, $site) || mb_strlen($full) > 65) ? $this->title : $full;
    }

    public function resolvedCanonical(): string
    {
        return $this->canonical ?? url()->current();
    }

    public function resolvedImage(): string
    {
        if ($this->ogImage) {
            return str_starts_with($this->ogImage, 'http') ? $this->ogImage : url($this->ogImage);
        }
        // Per-page card generated by `php artisan smukn:og`, keyed by route name; falls back to the brand default.
        $name = request()->route()?->getName();
        if ($name && is_file(public_path("images/og/{$name}.png"))) {
            return url("/images/og/{$name}.png");
        }

        return url(config('site.og_image'));
    }

    /** @return array<int, array<string, mixed>> */
    public function allJsonLd(): array
    {
        // One organisation and one website, referenced by @id from every page (no ratings, reviews or partnerships)
        $out = [[
            '@context' => 'https://schema.org',
            '@type' => 'Organization',
            '@id' => url('/').'#organization',
            'name' => config('site.name'),
            'url' => url('/'),
            'logo' => ['@type' => 'ImageObject', 'url' => url('/icon-512.png'), 'width' => 512, 'height' => 512],
            'email' => config('site.email'),
            'description' => config('site.default_description'),
        ]];
        if (! $this->noindex) {
            $page = ['@context' => 'https://schema.org', '@type' => 'WebPage', '@id' => $this->resolvedCanonical().'#webpage',
                'url' => $this->resolvedCanonical(), 'name' => $this->title, 'description' => $this->description, 'inLanguage' => 'en-GB',
                'isPartOf' => ['@id' => url('/').'#website'], 'publisher' => ['@id' => url('/').'#organization']];
            if ($this->lastReviewed) {
                $page['dateModified'] = $this->lastReviewed; // the date the page's facts were last reviewed, as shown on the page
            }
            $out[] = $page;
        }
        if ($this->breadcrumbs) {
            // the same trail as the visible breadcrumbs, which always start at Home
            $items = [['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => url('/')]];
            foreach (array_values($this->breadcrumbs) as $i => $c) {
                $item = ['@type' => 'ListItem', 'position' => $i + 2, 'name' => $c['label']];
                if (! empty($c['url'])) {
                    $item['item'] = $c['url'];
                }
                $items[] = $item;
            }
            $out[] = ['@context' => 'https://schema.org', '@type' => 'BreadcrumbList', 'itemListElement' => $items];
        }
        foreach ($this->jsonLd as $s) {
            $out[] = ['@context' => 'https://schema.org'] + $s;
        }

        return $out;
    }
}
